### ISSUE TITLE
Feature request: Save changes after exiting sandbox mode

### ISSUE THREAD

**Issue by alexfonseka** [AdamsLair/duality#729] opened 2019-07-06 23:13 UTC
Hey there,

As of right now, if you make changes to your component properties while the game is in sandbox mode, upon exiting sandbox mode, it will revert all your changes back to the default. This behavior has been somewhat counter-productive for me. 

Is there any possibility that the ability to save changes after exiting sandbox mode will be integrated into a future version of the editor? Is this something too difficult to implement given the current circumstances? I'm happy to assist with developing this feature. Even something quite simple like the ability to copy and paste component properties should help for the time being.

**Comment by ChristianGreiner** [comment] 2019-07-07 11:18
See https://github.com/AdamsLair/duality/issues/368

**Comment by ilexp** [comment] 2019-07-07 19:11
Closed as a duplicate of #368. Currently back from vacation and still catching up, will get back to you on #368 as I manage to find the time 🙂

**Closed by ilexp** 2019-07-07 19:11 UTC
