### ISSUE TITLE
Check if a Gameobject that uses a Renderer-Component owns a Transform-Component

### ISSUE THREAD

**Issue by ChristianGreiner** [AdamsLair/duality#398] opened 2016-09-19 18:02 UTC
I used a the Renderer-Component in empty GameObject.

The editor crashes with following [NullReferenceException](https://github.com/AdamsLair/duality/blob/7c6506eb46bd1f577cc303b3b5410cada5c6cf89/Duality/Components/Renderer.cs#L50):
`````
[Core] Error:   There was an error while Camera in "CamView Camera 0" was collecting drawcalls: NullReferenceException: Object reference not set to an instance of an object.
CallStack:
   at Duality.Components.Renderer.IsVisible(IDrawDevice device) in c:\projects\duality\Duality\Components\Renderer.cs:line 50
   at Duality.Components.DefaultRendererVisibilityStrategy.QueryVisibleRenderers(IDrawDevice device, RawList`1 targetList) in c:\projects\duality\Duality\Components\Other\DefaultRendererVisibilityStrategy.cs:line 44
   at Duality.Components.Camera.CollectDrawcalls() in c:\projects\duality\Duality\Components\Camera.cs:line 618
   at Duality.Components.Camera.RenderSinglePass(Rect viewportRect, Pass p) in c:\projects\duality\Duality\Components\Camera.cs:line 551
[Core] Error:   There was an error while Camera in "CamView Camera 0" was collecting drawcalls: NullReferenceException: Object reference not set to an instance of an object.
CallStack:
```` 

**// Edit:**
Suggestion:
Maybe the Renderer-Component should use the RequiredComponent-Attribute?

Peace out ✌️

**Comment by ilexp** [comment] 2016-09-20 17:26
Yup, that's a bug. Adding a `[RequiredComponent(typeof(Transform))]` should fix it. 

Note: Not all `ICmpRenderer` components actually need or have a Transform, but it seems like a reasonable choice to limit `Renderer`-derived components to the more common type of Transform-bound renderers.

**Comment by mfep** [comment] 2016-10-01 14:53
Hi,
There can be another problem, because it's already [added](https://github.com/AdamsLair/duality/blob/9d3211a1b3c4fe5d7fd01c7da06359cac2cc2333/Duality/Components/Renderer.cs#L14). However, implementing `ICmpRenderer` can be an issue, since interfaces cannot have properties.

**Comment by ilexp** [comment] 2016-10-01 15:06
Hm, indeed. An `ICmpRenderer` doesn't and shouldn't require a `Transform` though, as there are quite some renderer types that do not need to be located in space.

@ChristianGreiner Can you share the source code of your Component that causes this error? Are you sure you're using a `Renderer`-derived one, and not one that implements `ICmpRenderer`?

For the `Renderer` case, this would be a bug, because a derived Component should also derive its requirements. For the `ICmpRenderer` case, this would be by design and actually your responsibility to add the attribute to your concrete Component implementation.

**Comment by ilexp** [comment] 2016-10-01 15:24
Just checked, and the `RequiredComponent` attribute is already derived as it should. `SpriteRenderer` doesn't have one, but derives the required `Transform` component from `Renderer`, which is as it should be.

So.. can't really reproduce the error that was described above. We need more info on this, repro-steps or maybe a minimal example to illustrate.

**Comment by ChristianGreiner** [comment] 2016-10-01 17:25
@ilexp Oh, Jesus. I don't have the source anymore...
Let me to reproduce this bug...

**Comment by ChristianGreiner** [comment] 2016-10-01 17:58
Ok, I can't reproduce this bug. I'm sure that I used the Renderer-Class.

Instead, I found another bug:
Creat a new Component with the ICmpRenderer-Interface and add to the Scene.
After that remove the "Component-Class" in your Component so that your Component only implements the Interface "ICmpRenderer".

```CSharp
public class TestRenderer : ICmpRenderer
{
	[...]
}
```



Compile your plugin and...

```
[Core] ERR:   Error reading object: InvalidCastException: Object cannot be stored in an array of this type.
              CallStack:
                 at System.Array.InternalSetValue(Void* target, Object value)
                 at System.Array.SetValue(Object value, Int32[] indices)
                 at Duality.Serialization.XmlSerializer.ReadArray(XElement element, ObjectHeader header) in c:\projects\duality\Duality\Serialization\XmlSerializer.cs:line 551
                 at Duality.Serialization.XmlSerializer.ReadObjectBody(XElement element, ObjectHeader header) in c:\projects\duality\Duality\Serialization\XmlSerializer.cs:line 464
                 at Duality.Serialization.XmlSerializer.ReadObjectData(XElement element) in c:\projects\duality\Duality\Serialization\XmlSerializer.cs:line 446
[Core] ERR:   An error occurred in custom deserialization in object Id 2873377566 of type 'Dictionary<Type,Component>': ArgumentException: The value "Duality_.TestRenderer" is not of type "Duality.Component" and cannot be used in this generic collection.
              Parameter name: value
              CallStack:
                 at System.ThrowHelper.ThrowWrongValueTypeArgumentException(Object value, Type targetType)
                 at System.Collections.Generic.Dictionary`2.System.Collections.IDictionary.Add(Object key, Object value)
                 at Duality.Serialization.Surrogates.DictionarySurrogate.ReadData(IDataReader reader) in c:\projects\duality\Duality\Serialization\Surrogates\DictionarySurrogate.cs:line 60
                 at Duality.Serialization.XmlSerializer.ReadStruct(XElement element, ObjectHeader header) in c:\projects\duality\Duality\Serialization\XmlSerializer.cs:line 617
[Core] ERR:   Can't load Scene from 'Data\Scene.Scene.res', because an error occurred: 
              NullReferenceException: Object reference not set to an instance of an object.
              CallStack:
                 at Duality.GameObject.PerformSanitaryCheck() in c:\projects\duality\Duality\GameObject.cs:line 881
                 at Duality.Resources.Scene.OnLoaded() in c:\projects\duality\Duality\Resources\Scene.cs:line 1000
                 at Duality.Resource.Init(Resource res) in c:\projects\duality\Duality\Resource.cs:line 444
                 at Duality.Resource.Load[T](Serializer formatter, String resPath, Action`1 loadCallback, Boolean initResource) in c:\projects\duality\Duality\Resource.cs:line 421
[Core] Msg:   Assembly loaded: mscorlib.resources 4.0.0.0
[Edit] ERR:   Failed reloading plugins during runtime: NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
              CallStack:
                 bei Duality.Editor.Forms.ReloadCorePluginDialog.RestoreTemporaryData(WorkerInterface workInterface, Stream strScene, Stream strData) in c:\projects\duality\DualityEditor\Forms\ReloadCorePluginDialog.cs:Zeile 480.
                 bei Duality.Editor.Forms.ReloadCorePluginDialog.PerformPluginReload(WorkerInterface workInterface, Boolean& fullRestart) in c:\projects\duality\DualityEditor\Forms\ReloadCorePluginDialog.cs:Zeile 374.
                 bei Duality.Editor.Forms.ReloadCorePluginDialog.WorkerThreadProc(Object args) in c:\projects\duality\DualityEditor\Forms\ReloadCorePluginDialog.cs:Zeile 285.
[Edit] Msg:   Trying full restart...

```

**Comment by ilexp** [comment] 2016-10-01 21:08
> Instead, I found another bug:

Your Component no longer working is not actually a bug, but the editor should be able to handle this gracefully. Will look into it!

> Ok, I can't reproduce this bug. I'm sure that I used the Renderer-Class.

Okay, so.. I guess I'll close this issue for now, since none of us can reproduce the behavior, or have an idea how this could have been provoked. Please do comment & reopen (or create another one) should this occur again!

**Closed by ilexp** 2016-10-01 21:08 UTC
Labels: Bug, Core, Up For Grabs

**Comment by ilexp** [comment] 2016-10-01 22:15
Fixed the editor crash that was reported by @ChristianGreiner in the second last comment. Binary release in progress, check for updates in about 30 minutes.
