### ISSUE TITLE
Investigate CCD accuracy in physics simulation

### ISSUE THREAD

**Issue by deanljohnson** [AdamsLair/duality#264] opened 2016-01-10 10:58 UTC
Continuous Collision Detection(CCD) is meant to handle cases of fast moving objects that can leap over an obstacle in normal physics simulation. However, as mentioned in this thread 
http://forum.adamslair.net/viewtopic.php?f=16&t=668, CCD is not behaving as expected and doesn't seem to produce behavior different from regular physics simulation.

**Comment by ilexp** [comment] 2016-01-12 13:53
Just referencing isse #129 in case this turns out to require tweaking [CCD iteration settings](https://github.com/AdamsLair/farseerduality/blob/master/Settings.cs) on a per-project basis.

**Comment by ilexp** [comment] 2016-01-12 15:24
Tested this behavior and was able to reproduce it with sensor shapes, but not with non-sensors. Here's the test Scene that was used: [CCDTestScene.Scene.res.zip](https://github.com/AdamsLair/duality/files/87480/CCDTestScene.Scene.res.zip)

In this setup, the Bullet object flies towards the Target object at a velocity that would enable it to tunnel through. When `ContinuousCollision` is disabled in the Bullet, it will indeed tunnel through. When it is enabled, no tunneling occurs. However, when editing the Bullet to be a sensor shape, tunneling will occur either way.

With regard to the above find that sensor shapes are excluded from CCD explicitly, this is by design of the Farseer physics engine. Closing this issue for now, as there are enough workarounds / solutions for this and everything appears to work "as designed". Extending Farseer would be an option for future development, but is not actively pursued at this point.

> Edit: Why is PolygonRadius set to a quarter of its original value? The comment above says changing this could affect collision detection. Check whether it would be suitable to change it back if there is no apparent reason for it to be smaller.

Leaving this mystery as is for now. Never change a running system :)

**Closed by ilexp** 2016-01-12 15:24 UTC
Labels: Core, Task
