### ISSUE TITLE
TypeLoadException when editor wants to update packages

### ISSUE THREAD

**Issue by ChristianGreiner** [AdamsLair/duality#412] opened 2016-10-14 06:17 UTC
Today I started the editor on my laptop:
1. The editor stuck in a "bootloop". The editor downloaded the packages, copied them and downloaded them again... over and over again.
2. I downloaded a fresh Duality-Zip and deleted all duality-files in my project folder. The editor downloaded all necessary files again.. and doesn't start anymore.
The eventviewer prints this stracktraces:

```
Application: DualityEditor.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ComponentModel.Win32Exception
   at System.Diagnostics.Process.StartWithShellExecuteEx(System.Diagnostics.ProcessStartInfo)
   at System.Diagnostics.Process.Start(System.Diagnostics.ProcessStartInfo)
   at Duality.Editor.PackageManagement.PackageManager.ApplyUpdate(Boolean)
   at Duality.Editor.Program.Main(System.String[])
```

```
Application: DualityEditor.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeLoadException
   at Duality.Editor.PackageManagement.PackageManager.ApplyUpdate(Boolean)
   at Duality.Editor.Program.Main(System.String[])
```

**Comment by ilexp** [comment] 2016-10-14 14:06
I can't reproduce this using a fresh Duality installation.

1. Can you provide a list of steps to reproduce, or upload a zipped project that reproduces the issue?
2. Can you provide both `logfile_editor.txt` and `logfile_editor_prev.txt` of the project that fails to start?
3. Can you upload the `PackageConfig.xml` file of both projects, as well as take a screenshot of their `Source/Packages` folder contents?

**Comment by ilexp** [comment] 2016-10-14 14:27
Removing the Urgent label after @SirePi wasn't able to reproduce this either, both with a fresh install and by updating an old 2.0.4 version from October 2015. Seems to be more obscure than initially assumed.

If anyone else can reproduce this, please let me know.

**Comment by ChristianGreiner** [comment] 2016-10-15 12:41
I used git for sync my project on my pc and my laptop. So maybe that was the reason why it crashed...
I could fix the issue by deleting the "Packages" and restored some other files.
Now it works totally fine.

I've already rolled back the version on my laptop, so I think I haven't your desired files on my laptop anymore.

**Comment by ilexp** [comment] 2016-10-15 14:57
Hm.. okay, but thanks in any case for reporting. I'm closing this issue for now due to lack of information / repro steps, but if you stumble across it again, please either re-open or re-report it! Same for everyone else who might have info on this or ran into something similar. See my first comment above for info on what exactly we need.

**Closed by ilexp** 2016-10-15 14:57 UTC
Labels: Bug, Editor
