### ISSUE TITLE
Can't delete a Component if the GameObject misses one of its RequiredComponent

### ISSUE THREAD

**Issue by ChatPion** [AdamsLair/duality#382] opened 2016-08-29 21:01 UTC
#### Summary

Basically what title says

#### How to reproduce [Bugs]

- Create a Component A
- Add Component A to a GameObject
- Create Component B
- Add B as RequiredComponent for A
- You can't delete A as long as you don't add B to the GameObject, 
EDIT : you must do it in the object inspector

#### Workaround [Bugs]

- Add missing RequiredComponent to the GameObject
- EDIT : Right-click + delete in the scene view works.

**Comment by SirePi** [comment] 2016-09-30 13:35
It appears this is no longer the case? I tried following the instructions but the Component A is being deleted without problems

**Comment by ilexp** [comment] 2016-09-30 15:55
Since this issue wasn't addressed in the mean time, I suspect that the reproduction steps might miss a step. 

@ChatPion Can you re-check if the steps above reproduce the error? Anything unmentioned to be aware of?

**Comment by ChatPion** [comment] 2016-09-30 17:33
This is strange.

Here is an ultra minimalistic project where I litterally followed every step.
[Duality Application.zip](https://github.com/AdamsLair/duality/files/503488/Duality.Application.zip)

I get this weird silly message : 
![2016-09-30_19-29-28](https://cloud.githubusercontent.com/assets/3697923/19000754/a08c6366-8744-11e6-9df1-d37bc4deb40c.png)

**Comment by ilexp** [comment] 2016-09-30 22:01
Uhm.. what you're doing there is specifying a cyclic requirement. This can't work out. A component shouldn't require itself.

Can you reproduce the same behavior without a cyclic reference?

**Comment by mfep** [comment] 2016-10-01 15:42
This issue happens, when the component dependencies change with recompiling the GamePlugin, @ChatPion means *create a .cs file, fill it, and recompile* by *Create*.
I propose that every plugin-reload should come with an iteration over the components if everyone's dependency is met, and add the missing components. Same for scene loading.

**Comment by mfep** [comment] 2016-10-01 16:27
Solution is on the way. Pull request incoming (most probably tomorrow).

**Comment by ilexp** [comment] 2016-10-01 21:17
> I propose that every plugin-reload should come with an iteration over the components if everyone's dependency is met, and add the missing components. Same for scene loading.

I don't think this is a good idea. Suppose you have a scene with 2000 objects, each having, say, 5 Components, you're going to check dependencies for 10000 Components every time you reload the plugin, only to catch that one corner case? 

The editor shouldn't take action here. If a user decides that an existing Component has another requirement, it should be the users responsibility to add this to existing instances. I don't want everyone's editor experience to be worse for a case that I assume to be quite rare.

Instead, the issue that is reported here is specifically not being able to remove a Component because of missing requirements. This is actually a problem with the algorithm that determines whether it is safe to remove a certain Component. My bet would be on fixing that instead. Should be able to locate the responsible code starting [somewhere here](https://github.com/AdamsLair/duality/blob/9d3211a1b3c4fe5d7fd01c7da06359cac2cc2333/Duality/Component.cs#L362-L393).

Still up for that PR?

**Comment by mfep** [comment] 2016-10-01 22:11
Hmm, right. Actually, the idea was to check every scene load if there are unmet dependencies, and correct them. Not in the editor, in the Core. Thus incorrect state would have been avoided entirely. Of course lot of iteration at a high number of objects...
I'll probably investigate the phenomenon once again, and PR as you requested. It's Hacktober after all! 😄

**Comment by ilexp** [comment] 2016-10-01 22:23
> I'll probably investigate the phenomenon once again, and PR as you requested. It's Hacktober after all! 😄

Nice, will look out for that 👍

**Comment by ilexp** [comment] 2016-10-02 08:53
Fixed by @mfep in the referencing issue, though no binary release yet. Closing this.

**Closed by ilexp** 2016-10-02 08:53 UTC
Labels: Bug, Editor, Up For Grabs
