### ISSUE TITLE
NullReferenceException in CamView-Plugin

### ISSUE THREAD

**Issue by ChristianGreiner** [AdamsLair/duality#400] opened 2016-09-26 21:38 UTC
I edited a property of two prefabs by selecting them (shift + select). After that clicked apply and then the editor throws this exception:

```
[Edit] Error:   An error occurred during a core update: NullReferenceException: Object reference not set to an instance of an object.
CallStack:
   at Duality.Editor.Plugins.CamView.CamViewStates.SceneEditorCamViewState.IsAffectedByParent(GameObject child, GameObject parent) in c:\projects\duality\DualityEditorPlugins\CamView\CamViewStates\SceneEditor\SceneEditorCamViewState.cs:line 339
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Duality.Editor.Plugins.CamView.CamViewStates.SceneEditorCamViewState.<EditorForm_SelectionChanged>b__2a(GameObject o) in c:\projects\duality\DualityEditorPlugins\CamView\CamViewStates\SceneEditor\SceneEditorCamViewState.cs:line 328
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Duality.Editor.Plugins.CamView.CamViewStates.SceneEditorCamViewState.EditorForm_SelectionChanged(Object sender, SelectionChangedEventArgs e) in c:\projects\duality\DualityEditorPlugins\CamView\CamViewStates\SceneEditor\SceneEditorCamViewState.cs:line 329
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Duality.Editor.DualityEditorApp.OnSelectionChanged(Object sender, Category changedCategoryFallback, SelectionChangeReason changeReson) in c:\projects\duality\DualityEditor\DualityEditorApp.cs:line 1137
   at Aga.Controls.Tree.TreeViewAdv.OnSelectionChanged() in c:\Stuff\svn\Projects\AdamsLair.TreeViewAdv\Aga.Controls\Tree\TreeViewAdv.cs:line 114
   at Aga.Controls.Tree.TreeViewAdv.UpdateSelection() in c:\Stuff\svn\Projects\AdamsLair.TreeViewAdv\Aga.Controls\Tree\TreeViewAdv.cs:line 1015
   at Aga.Controls.Tree.TreeViewAdv._model_NodesRemoved(Object sender, TreeModelEventArgs e) in c:\Stuff\svn\Projects\AdamsLair.TreeViewAdv\Aga.Controls\Tree\TreeViewAdv.cs:line 1343
   at Aga.Controls.Tree.TreeModel.OnNodeRemoved(Node parent, Int32 index, Node node) in c:\Stuff\svn\Projects\AdamsLair.TreeViewAdv\Aga.Controls\Tree\TreeModel.cs:line 121
   at Aga.Controls.Tree.Node.NodeCollection.RemoveItem(Int32 index) in c:\Stuff\svn\Projects\AdamsLair.TreeViewAdv\Aga.Controls\Tree\Node.cs:line 61
   at System.Collections.ObjectModel.Collection`1.Remove(T item)
   at Duality.Editor.Plugins.SceneView.SceneView.Scene_GameObjectUnregistered(Object sender, GameObjectEventArgs e) in c:\projects\duality\DualityEditorPlugins\SceneView\Modules\SceneView.cs:line 1752
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Duality.Resources.Scene.OnGameObjectRemoved(GameObjectEventArgs args) in c:\projects\duality\Duality\Resources\Scene.cs:line 283
   at Duality.Resources.Scene.objectManager_GameObjectRemoved(Object sender, GameObjectEventArgs e) in c:\projects\duality\Duality\Resources\Scene.cs:line 953
   at Duality.GameObjectManager.OnObjectRemoved(GameObject obj) in c:\projects\duality\Duality\Utility\GameObjectManager.cs:line 207
   at Duality.GameObjectManager.Flush() in c:\projects\duality\Duality\Utility\GameObjectManager.cs:line 154
   at Duality.Resources.Scene.RunCleanup() in c:\projects\duality\Duality\Resources\Scene.cs:line 614
   at Duality.Resources.Scene.Update() in c:\projects\duality\Duality\Resources\Scene.cs:line 508
   at Duality.DualityApp.EditorUpdate(IEnumerable`1 updateObjects, Boolean freezeScene, Boolean forceFixedStep) in c:\projects\duality\Duality\DualityApp.cs:line 548
   at Duality.Editor.DualityEditorApp.Application_Idle(Object sender, EventArgs e) in c:\projects\duality\DualityEditor\DualityEditorApp.cs:line 1288

```

I've tried this again, but it didn't happened again.. so jeah.. I hope the stacktrace can help

**Comment by ilexp** [comment] 2016-09-27 15:47
Thanks for reporting! Labeled, categorized and awaiting investigation.

**Comment by ilexp** [comment] 2016-10-03 11:59
Couldn't reproduce this bug either, but restructured and simplified some Camera View code that might fix the exception. This is really just a guess though. Release is in progress, check for package updates in about 30 minutes.

Closing this for now. Please re-open should this bug occur again. The callstack will have changed by then, providing more insight into what's happening due to cleaned up code.

**Closed by ilexp** 2016-10-03 11:59 UTC
Labels: Bug, Editor
