### ISSUE TITLE
Object Visibility Filter in Camera View Remembers Filtering for Non-Existent / Invalid Component Types

### ISSUE THREAD

**Issue by ChatPion** [AdamsLair/duality#419] opened 2016-10-22 17:15 UTC
_New Issue Text_

As described below, it is possible to select a Component for filtering in the Camera View, then delete the Component type entirely, rebuild the plugin and still have the (now invalid) filtering active, not displaying any object. This is likely also a problem even for still existing types after plugin reload, since the stored `Type` instances will no longer be valid.

------
_Original Issue Text:_

Right now, to hide a gameobject, we have to select all of its components. This is annoying because if I want to hide all my SpriteRenderers, I'll have to hide Transforms too for example.

How to fix this ? 
- easiest option : hide a gameoject if one of its component is hidden
- hardest but maybe best option : make it so we can hide components separately. For example, being able to hide SpriteRenderers while keeping all RigidbodyRenderer.

By the way, is it even useful to see in the list components that doesn't render anything ?

**Comment by ilexp** [comment] 2016-10-23 07:56
The Camera View menu in question is not actually a "hide" menu, but a "filter" menu. It is not designed to help you with the task of hiding all objects of type X, but of displaying only objects that have a certain Component Y. There is currently no hiding functionality by type.

> easiest option : hide a gameoject if one of its component is hidden

This would break the filter functionality the menu was designed for.

> make it so we can hide components separately. For example, being able to hide SpriteRenderers while keeping all RigidbodyRenderer.

You can achieve this by just selecting RigidbodyRenderer in the filter menu, and nothing else.

> By the way, is it even useful to see in the list components that doesn't render anything ?

Yes, because you might for example be interested in all your characters, so you select "CharacterController" for filtering and will only see the objects that have one of those - even if the CharacterController Component _itself_ does not render anything.

In addition to the Camera View object filtering, you can also hide objects entirely in the Scene View by right-clicking on them and using the Lock / Hide option. Clicking on it will cycle through the None / Lock / Hide options and since it will affect all child objects as well, you can easily group your objects in empty GameObjects (as "folders") and then hide or show an entire group at once. Not sure if that helps in your case, but I use that a lot.

After reading my response, do you have a proposal for improvement on the matter?

**Comment by ChatPion** [comment] 2016-10-23 10:11
I can see the logic behind now. I missed the fact that it is a filter menu. 

But I was thinking about about filtering GameObjects with many components. For example, if I have two GameObjects, one with A, B, C and D components, and another with A, B, C and E, and let's say that they are instantiated a lot in such a way that hiding then in the Scene View is pretty complicated (probably a bad design, but let's roll with that). Now, if I want to only show GameObjects with D, I'll have to uncheck A, B, C and E, which may seem counter-intuitive.

I think what bothered me the most was that in almost any case I have to uncheck Transform to filter anything. But following your reasoning, this feature is fine as it is now.

**Comment by ilexp** [comment] 2016-10-23 11:43
The question is, why is any Component checked in the first place? By default, all Components in the filter menu are unchecked (which means "don't filter"), so in the scenario you described all you'd have to do is check the D Component?

**Comment by ChatPion** [comment] 2016-10-23 12:29
Alright, it seems that I have a buggy project : with a fresh project, checking one component will only show components with that component (which is quite logical), but in my project, unchecking everything will show nothing.

I have a suspicion : I think I may have checked a component, then deleted the component. Now, Dualitor thinks that I only want to see a component that I don't use anymore in my scene. 

I just tested in a new project and my suspicion is confirmed. I think I may have found a bug.

**Comment by ilexp** [comment] 2016-10-23 12:35
> I have a suspicion : I think I may have checked a component, then deleted the component. Now, Dualitor thinks that I only want to see a component that I don't use anymore in my scene.

I think you're right. This needs to be investigated as a potential bug. Editing the issue to match this.

**Comment by ChatPion** [comment] 2016-10-23 19:34
I'm currently working on this.
What is the best option : keeping the component not used filtered and ignore it when applying the filters, or unfilter every component that aren't used anymore ?

**Comment by ilexp** [comment] 2016-10-23 20:51
You have to distinguish two cases:

1. The Component type by which is filtered exists, but there is no Component of that type in the current Scene. In this case, keep all as is. This is a valid case. Nothing to do here.
2. The Component type by which is filtered no longer exists, so it will never yield any filtering results again. In that case it needs to be removed.

Actually, there may be a more general problem to this: Since object visibility [is stored in a Type set](https://github.com/AdamsLair/duality/blob/master/DualityEditorPlugins/CamView/Modules/CamView.cs#L175), rebuilding the core plugin will invalidate _all_ entries, not just the ones that belong to no longer existent types. The same is true for each [CamViewState's local object visibility](https://github.com/AdamsLair/duality/blob/master/DualityEditorPlugins/CamView/CamViewStates/CamViewState.cs#L63) setting.

This needs to be fixed either with a type-remapping on plugin reload, or by storing type id strings in the first place. However, the CamView part needs some sort of a Type caching mechanism for performance reasons, so there is probably no way around a `HashSet<Type>`.

**Comment by ChatPion** [comment] 2016-10-24 12:50
I was just going to suggest this !
And I'm still working on this ! (you know, hacktoberfest and stuff...)

**Comment by ilexp** [comment] 2016-10-26 16:40
### Progress

- @ChatPion changed the menu implementation to always display filtered Component types, even if they're not in the current Scene.

### Immediate ToDo

- Add an alternative icon indicating whether any filter is currently active.
- Fix the plugin reload issue that was outlined before.

**Comment by ilexp** [comment] 2016-10-26 19:19
Done. Package Update will likely follow in the next few days.

**Closed by ilexp** 2016-10-26 19:19 UTC
Labels: Bug, Editor
