### ISSUE TITLE
Extending the CorePlugin API for recognizing whether plugin is running or has been stoped in the Dualitor

### ISSUE THREAD

**Issue by FaithlessQ** [AdamsLair/duality#557] opened 2017-08-15 07:12 UTC
### Summary

An extension of the CorePlugin API would be appreciated which enables the plugin to determine the running state in Dualitor. I suggest it should be possible on plugin level to know the following things:

* Dualitor starts running the game
* Dualitor pauses the game
* Dualitor resumes from pause
* Dualitor stops the game completly

With these four events/callbacks you have the maximum flexibility to react on editor interactions.

### Analysis [Feature Requests]

In my case my benefit is, that I am able to do core plugin specific cleanup on stopping the execution within the editor. Using the Launcher the plugin can rely on the Terminate event on DualityApp. But this does not trigger in editor mode which is understandable. In my case I use background tasks for networking across multiple scenes, so I have to shut them down on stop to ensure a clean state of the plugin. Next time it runs in the editor it can start right from the beginning.

I also will need the "start running the game" signal later. It can be used excellently for starting right in the middle of the game in a specific scene. Normally you need some scenes before to get to that point, but this is time consuming to do it every time you want to debug. So you can change your game start scene to the middle of the game and use a specific debug component which gets a event from your CorePlugin that it has been started running in the editor. The network server my core plugin is connecting to will have a rejoin capability, so the core plugin can right join a specific or the last session, when it knows it is started within the editor.  Normally the establishing of the server connection have to be done much earlier, but via the special editor event it can be done directly in a debug component within the scene. The development experience would be really enhanced by this for me.

It may also be a nice benefit to enable the determiniation of pause and resume in Dualitor. Then you can decide yourself if you need to stop something in the background or not when editor pauses the game. In my specific case I will not need this feature, because the networking should even be done in pause, otherwise a disconnect may happen which is not my intention in pause. But I still can imagine cases where even in pause, game related background stuff have to be adjusted or also paused. A case where I think of may be a simulation game, where the game calculates the simulation stuff in background because it's much to time consuming to do in the Update call. It may be wise to also stop any simulation on pause, so the game will not go on while rendering is stopped.

Potential API extension:
An extension of Duality.CorePlugin may be solution. I personally already like the OnExecContextChanged handling. May be one new method with something similar and a argument for the new state (run, pause, resume and stop) the editor is changing in would be sufficient. 

Because of the relation of this feature to the editor it's best not to call the new method, when the game runs through the Launcher respectively outside of Dualitor. So it will remain exclusive for editor behaviour/interaction.

**Comment by ilexp** [comment] 2017-08-15 16:43
Your use case makes a lot of sense, but I'd approach the solution in a slightly different way. In general, I don't think the core should have knowledge about editor state, including sandbox paused / playing states. Besides potential game / editor inconsistencies, Duality can also be hosted in any non-launcher / non-editor environment that someone might come up with, and the last thing someone would want to worry about is emulating things that were hard-wired to one environment or the other.

Instead, the goal that I would pick for this issue is to make sure there are facilities allowing core plugins to handle plugin / game / application lifecycle events that make sense regardless of execution environment.

Here are some early thoughts on this:

- I reconsidered the fact that the game **execution context** switches to edit mode when pausing the sandbox - I'm currently leaning towards changing that behavior, so that the execution context will be game mode for the entirety of sandbox activity. Pausing the sandbox is still part of game execution - all the objects have been initialized that way, they just don't update right now. Will have to check that this doesn't break anything, but there's that.
- Components have access to a range of handler interfaces for initialization and shutdown at various points in their lifecycle, as well as updates. It would make sense if the CorePlugin had similar facilities, so it can act as a **plugin-global init / shutdown** counterpart to them. A set of virtual `OnActivate` / `OnDeactivate` methods might already be enough: They'd be called at the beginning and end of the game simulation, regardless of whether that is on launcher start / quit or on sandbox enter / leave.

None of the above requires core knowledge about editor states, and it feels like a somewhat natural extension of what's already there. Would that help in your case?

> A case where I think of may be a simulation game, where the game calculates the simulation stuff in background because it's much to time consuming to do in the Update call. It may be wise to also stop any simulation on pause, so the game will not go on while rendering is stopped.

I think this would be better solved using the regular sync mechanisms. You probably wouldn't want to do more than one full background update per main thread frame or work item, so you'd probably look out for `Time.FrameCount` or a custom work item queue as a barrier, which would prevent that simulation to continue in a paused sandbox, simply because there are no more updates incrementing the frame counter or adding work items.

**Comment by FaithlessQ** [comment] 2017-08-16 06:30
> Instead, the goal that I would pick for this issue is to make sure there are facilities allowing core plugins to handle plugin / game / application lifecycle events that make sense regardless of execution environment.

While I totally understand not to be specific to the execution context and implementing a general API, I am only a bit surprised, because  the core plugin knows at least it's execution context with DualityApp.ExecContext, so there is already something specific a core plugin should not need to know, you could argue :)

> * I reconsidered the fact that the game execution context switches to edit mode when pausing the sandbox - I'm currently leaning towards changing that behavior, so that the execution context will be game mode for the entirety of sandbox activity. Pausing the sandbox is still part of game execution - all the objects have been initialized that way, they just don't update right now. Will have to check that this doesn't break anything, but there's that.
> * Components have access to a range of handler interfaces for initialization and shutdown at various points in their lifecycle, as well as updates. It would make sense if the CorePlugin had similar facilities, so it can act as a plugin-global init / shutdown counterpart to them. A set of virtual OnActivate / OnDeactivate methods might already be enough: They'd be called at the beginning and end of the game simulation, regardless of whether that is on launcher start / quit or on sandbox enter / leave.

> None of the above requires core knowledge about editor states, and it feels like a somewhat natural extension of what's already there. Would that help in your case?

Yes, that would help in my case. Either the first or the second implementation will enable a clean reset on stopping the execution within Dualitor. Because the second approach with OnActivate / OnDeactivate will be called independently of the execution context I would also appreciate the first implementation, because it will enhance my development experience for jumping right into the middle of the game for debugging and play testing as already mentioned.

> I think this would be better solved using the regular sync mechanisms. You probably wouldn't want to do more than one full background update per main thread frame or work item, so you'd probably look out for Time.FrameCount or a custom work item queue as a barrier, which would prevent that simulation to continue in a paused sandbox, simply because there are no more updates incrementing the frame counter or adding work items

Yep, this would be a solution to the simulation case.

**Comment by ilexp** [comment] 2017-08-17 16:40
> While I totally understand not to be specific to the execution context and implementing a general API, I am only a bit surprised, because the core plugin knows at least it's execution context with DualityApp.ExecContext, so there is already something specific a core plugin should not need to know, you could argue :)

Having one breach already doesn't mean I'd like to add more 😄

> Yes, that would help in my case. Either the first or the second implementation will enable a clean reset on stopping the execution within Dualitor. Because the second approach with OnActivate / OnDeactivate will be called independently of the execution context I would also appreciate the first implementation, because it will enhance my development experience for jumping right into the middle of the game for debugging and play testing as already mentioned.

Great. I'll take a look at both of the solution approaches I mentioned.

**Comment by ilexp** [comment] 2017-08-20 13:38
### Progress

- Investigated execution context checks for `Game` vs. `Editor`.
  - FlapOrDie [MusicManager.OnInit](https://github.com/AdamsLair/duality/blob/bdb98a1b6a6e11c233ebd60da1e6ef268d8e5910/Samples/FlapOrDie/Components/MusicManager.cs#L25): Play music only in game mode.
  - Physics [PhysicsSampleController.OnInit](https://github.com/AdamsLair/duality/blob/bdb98a1b6a6e11c233ebd60da1e6ef268d8e5910/Samples/Physics/PhysicsSampleController.cs#L217): Retrieve full scene list only in game mode.
  - DualStickSpaceShooter [CorePlugin.OnBeforeUpdate](https://github.com/AdamsLair/duality/blob/bdb98a1b6a6e11c233ebd60da1e6ef268d8e5910/Samples/DualStickSpaceShooter/CorePlugin.cs#L20): Could be replaced with plugin game activate API.
  - Steering [CorePlugin.OnBeforeUpdate](https://github.com/AdamsLair/duality/blob/bdb98a1b6a6e11c233ebd60da1e6ef268d8e5910/Samples/Steering/CorePlugin.cs#L10): Update only while in-game.
  - Core [ProfileRenderer.IsVisible](https://github.com/AdamsLair/duality/blob/bdb98a1b6a6e11c233ebd60da1e6ef268d8e5910/Source/Core/Duality/Components/Diagnostics/ProfileRenderer.cs#L137): Display profiler data only while in game mode.
  - Core [RigidBody.OnUpdate](https://github.com/AdamsLair/duality/blob/bdb98a1b6a6e11c233ebd60da1e6ef268d8e5910/Source/Core/Duality/Components/Physics/RigidBody.cs#L1139): Enable body when in game mode. This would be obsolete when changing sandbox behavior towards constantly using the `Game` context, as this is a workaround for an issue with having context switches at runtime inside an active scene without reloading it.
  - Core [RigidBody.InitBody](https://github.com/AdamsLair/duality/blob/bdb98a1b6a6e11c233ebd60da1e6ef268d8e5910/Source/Core/Duality/Components/Physics/RigidBody.cs#L948): Only enable body when in game mode for optimization purposes.
  - Core [ShapeInfo.RequireFullBodyUpdate](https://github.com/AdamsLair/duality/blob/bdb98a1b6a6e11c233ebd60da1e6ef268d8e5910/Source/Core/Duality/Components/Physics/ShapeInfo.cs#L154): Not entirely clear which cases this check accounts for, but looks like it tries to determine whether the physics system is already up and simulating.
  - Core [SoundEmitter.OnUpdate](https://github.com/AdamsLair/duality/blob/bdb98a1b6a6e11c233ebd60da1e6ef268d8e5910/Source/Core/Duality/Components/SoundEmitter.cs#L213): Unclear. Seems to stop audio when pausing the sandbox. Can probably removed entirely, but test before and after to be sure.
  - Core [SoundListener.OnInit](https://github.com/AdamsLair/duality/blob/bdb98a1b6a6e11c233ebd60da1e6ef268d8e5910/Source/Core/Duality/Components/SoundListener.cs#L24): Only make itself the current listener on activation when not in the editor. Likely to not interfere with editor camera view listeners.
  - Core [GameObject.ctor](https://github.com/AdamsLair/duality/blob/bdb98a1b6a6e11c233ebd60da1e6ef268d8e5910/Source/Core/Duality/GameObject.cs#L307): Keep prefab link in editor, just clone at runtime.
  - Core [Scene.OnEntered](https://github.com/AdamsLair/duality/blob/bdb98a1b6a6e11c233ebd60da1e6ef268d8e5910/Source/Core/Duality/Resources/Scene.cs#L274): Break prefab links at runtime.
  - Core [Time.TickFrame](https://github.com/AdamsLair/duality/blob/bdb98a1b6a6e11c233ebd60da1e6ef268d8e5910/Source/Core/Duality/Time.cs#L140): Only advance game timer while in game mode. This will break in a paused sandbox, but can be addressed by using a different code path when called by `DualityApp.EditorUpdate`.
  - Core [VisualLog.PrepareRenderLogEntries](https://github.com/AdamsLair/duality/blob/bdb98a1b6a6e11c233ebd60da1e6ef268d8e5910/Source/Core/Duality/Utility/Log/VisualLog.cs#L58): Only spawn a visual log renderer at runtime.
  - Editor [DualityEditorApp.Application_Idle](https://github.com/AdamsLair/duality/blob/bdb98a1b6a6e11c233ebd60da1e6ef268d8e5910/Source/Editor/DualityEditor/DualityEditorApp.cs#L1279): Execution of single-step updates in a paused sandbox in a temporary `Game` mode. This will be obsolete after keeping the execution context in `Game` when pausing the sandbox.
  - CamView [CamViewState.OnUpdateState](https://github.com/AdamsLair/duality/blob/bdb98a1b6a6e11c233ebd60da1e6ef268d8e5910/Source/Plugins/EditorModules/CamView/CamViewStates/CamViewState.cs#L527): Re-draw every update while in game mode. This will re-draw every frame even when paused after the proposed change. Consider changing code to actually check sandbox state instead.
  - CamView [ObjectEditorCamViewState.OnUpdateState](https://github.com/AdamsLair/duality/blob/bdb98a1b6a6e11c233ebd60da1e6ef268d8e5910/Source/Plugins/EditorModules/CamView/CamViewStates/ObjectEditor/ObjectEditorCamViewState.cs#L731): Update selection stats every update while in game mode. This will trigger even when paused after the proposed change. Consider changing code to actually check sandbox state instead.
  - ObjectInspector [ObjectInspector.AfterUpdateDualityApp](https://github.com/AdamsLair/duality/blob/bdb98a1b6a6e11c233ebd60da1e6ef268d8e5910/Source/Plugins/EditorModules/ObjectInspector/Modules/ObjectInspector.cs#L168): Periodically update displayed values while in game mode. This will trigger even when paused after the proposed change. Consider changing code to actually check sandbox state instead.

### Immediate ToDo

- Introduce `OnGameStarted` and `OnGameEnded` API to `CorePlugin` to be called before the first / after the last update in game execution context. Should behave similar when running or exiting the launcher as when entering / leaving sandbox mode in the editor.
- Replace or remove as many of the above execution context checks as possible.
- Make sure the remaining execution context checks will still work as intended when changing the sandbox paused context to `Game`.
- Change the sandbox paused context to `Game`.
- Trigger a binary release
- Merge to v3.0
- Consider changing `CorePlugin` API in v3.0 to distinguish between regular (game) updates and editor updates, so no execution context checks are required for the most common case of game updates.
  - `OnBeforeUpdate` / `OnAfterUpdate`
  - `OnBeforeEditorUpdate` / `OnAfterEditorUpdate`

**Comment by ilexp** [comment] 2017-08-20 19:19
### Progress

- Created the `coreplugin-execcontext-wip` branch to work on this.
- Removed, replaced or otherwise dealt with the following execution context dependencies:
  - Core [RigidBody.OnUpdate](https://github.com/AdamsLair/duality/blob/bdb98a1b6a6e11c233ebd60da1e6ef268d8e5910/Source/Core/Duality/Components/Physics/RigidBody.cs#L1139): Enable body when in game mode. This would be obsolete when changing sandbox behavior towards constantly using the `Game` context, as this is a workaround for an issue with having context switches at runtime inside an active scene without reloading it.
  - Core [SoundEmitter.OnUpdate](https://github.com/AdamsLair/duality/blob/bdb98a1b6a6e11c233ebd60da1e6ef268d8e5910/Source/Core/Duality/Components/SoundEmitter.cs#L213): Unclear. Seems to stop audio when pausing the sandbox. Can probably removed entirely, but test before and after to be sure.
  - Core [Time.TickFrame](https://github.com/AdamsLair/duality/blob/bdb98a1b6a6e11c233ebd60da1e6ef268d8e5910/Source/Core/Duality/Time.cs#L140): Only advance game timer while in game mode. This will break in a paused sandbox, but can be addressed by using a different code path when called by `DualityApp.EditorUpdate`.
  - Editor [DualityEditorApp.Application_Idle](https://github.com/AdamsLair/duality/blob/bdb98a1b6a6e11c233ebd60da1e6ef268d8e5910/Source/Editor/DualityEditor/DualityEditorApp.cs#L1279): Execution of single-step updates in a paused sandbox in a temporary `Game` mode. This will be obsolete after keeping the execution context in `Game` when pausing the sandbox.
  - CamView [CamViewState.OnUpdateState](https://github.com/AdamsLair/duality/blob/bdb98a1b6a6e11c233ebd60da1e6ef268d8e5910/Source/Plugins/EditorModules/CamView/CamViewStates/CamViewState.cs#L527): Re-draw every update while in game mode. This will re-draw every frame even when paused after the proposed change. Consider changing code to actually check sandbox state instead.
  - CamView [ObjectEditorCamViewState.OnUpdateState](https://github.com/AdamsLair/duality/blob/bdb98a1b6a6e11c233ebd60da1e6ef268d8e5910/Source/Plugins/EditorModules/CamView/CamViewStates/ObjectEditor/ObjectEditorCamViewState.cs#L731): Update selection stats every update while in game mode. This will trigger even when paused after the proposed change. Consider changing code to actually check sandbox state instead.
  - ObjectInspector [ObjectInspector.AfterUpdateDualityApp](https://github.com/AdamsLair/duality/blob/bdb98a1b6a6e11c233ebd60da1e6ef268d8e5910/Source/Plugins/EditorModules/ObjectInspector/Modules/ObjectInspector.cs#L168): Periodically update displayed values while in game mode. This will trigger even when paused after the proposed change. Consider changing code to actually check sandbox state instead.
- Changed sandbox behavior to remain in `Game` context when paused.
- Simplified some of the `DualityApp.EditorUpdate` code.

### Immediate ToDo

- Introduce `OnGameStarted` and `OnGameEnding` API to `CorePlugin` to be called before the first / after the last update in game execution context. Should behave similar when running or exiting the launcher as when entering / leaving sandbox mode in the editor.
- Test the new behavior in a core plugin.
- Check all the sample projects whether they're working correctly.
- Trigger a binary release
- Merge to v3.0
- Consider changing `CorePlugin` API in v3.0 to distinguish between regular (game) updates and editor updates, so no execution context checks are required for the most common case of game updates.
  - `OnBeforeUpdate` / `OnAfterUpdate`
  - `OnBeforeEditorUpdate` / `OnAfterEditorUpdate`
  - Alternatively, consider just changing behavior and not introducing editor update variants at all, since this doesn't seem to be used right now and it shouldn't be a common use case.

**Comment by ilexp** [comment] 2017-08-21 17:04
### Progress

- Introduced `OnGameStarting` / `OnGameEnded` API to `CorePlugin`.
- Verified that the new API is called and execution contexts are switched as intended in a testing core plugin.

### Immediate ToDo

- Check all the sample projects whether they're working correctly.
- Trigger a binary release
- Merge to v3.0
- Consider changing `CorePlugin` API in v3.0 to distinguish between regular (game) updates and editor updates, so no execution context checks are required for the most common case of game updates.
  - `OnBeforeUpdate` / `OnAfterUpdate`
  - `OnBeforeEditorUpdate` / `OnAfterEditorUpdate`
  - Alternatively, consider just changing behavior and not introducing editor update variants at all, since this doesn't seem to be used right now and it shouldn't be a common use case.

**Comment by ilexp** [comment] 2017-08-22 08:30
### Progress

- Merged back the feature branch of this issue to `master`.
- Triggered a binary release.
- Merged to `develop-v3.0`.
- Changed behavior in v3.0 branch to only call before / after update events in an active game simulation, so they're always wrapped by a game started / game ended pair of calls.

**Closed by ilexp** 2017-08-22 08:30 UTC
Labels: Core, Editor, Feature

**Comment by FaithlessQ** [comment] 2017-08-22 17:57
Thank you very much for implementing this new feature so quick and for changing the behaviour regarding the pause. Seemed like a lot work you had to be done.
I already tested it and it behaves exactly as you described. This will make testing and the use of Dualitor much easier for me :)
