### ISSUE TITLE
Error when importing two fonts of the same family

### ISSUE THREAD

**Issue by SirePi** [AdamsLair/duality#178] opened 2015-03-14 13:46 UTC
Following the conversation [here](http://forum.adamslair.net/viewtopic.php?f=20&t=372#p2026), I made a couple tests and I found that if you import a font inside Duality, remove the font, then try to import the same font or even another in the same family, Duality will refuse to import the file with a generic "file type not supported" error message.

(for this test I have used 'Arial Black' and 'Arial Italic' from the Windows' Font directory)
How to reproduce:
* Open a fresh copy of Duality
* Import (drag and drop) Arial Black in the project. The font will be imported.
* Remove Arial Black from the project.
* Import Arial Italic in the project. It won't work and you will get the error.

Restarting the editor fixes the issue, until you do it again :)

**Comment by AdamsLair** [comment] 2015-03-14 13:58
Yep, this is "expected" behavior, although not really the one that is preferable. There should be done something about it, but I am not sure how to handle this.

- Duality uses an internal cache for Font families. This is [provided by .Net](https://msdn.microsoft.com/en-us/library/system.drawing.text.privatefontcollection(v=vs.110).aspx) and there's nothing Duality actually does with it, except adding Font data.
- It doesn't support adding the same Font family multiple times and I'm not even sure that this *should* be supported either.
- The error is caused by the fact that each imported Font remains in that cache and it won't allow to add the same family multiple times.

One way to handle this would be to keep a [PrivateFontCollection](https://msdn.microsoft.com/en-us/library/system.drawing.text.privatefontcollection(v=vs.110).aspx) for each Font, or instantiate it temporarily and get rid of it again later.

Will need to investigate whether this is a good solution.

**Comment by SirePi** [comment] 2015-03-14 14:06
Hmm.. I understand where this is coming from. 
I agree that it shouldn't be that big of a deal.. I only noticed that because I imported the wrong font style and wanted to import another one (a quite rare case I think)

Maybe it could be enough to put an appropriate warning message if the PrivateFontCollection already contains the Family of the new font. Something like "Cannot import this font now, please restart to rebuild font cache."

**Comment by AdamsLair** [comment] 2015-03-14 14:11
I'm sure there must be a way to do this properly - I'm just not sure, which one it is yet. In any case, thanks for pointing this out. :) It's bad usability and it needs to be addressed.

**Comment by AdamsLair** [comment] 2015-05-26 09:41
This should be addressed in the course of [getting rid of System.Drawing in v2.0](https://github.com/AdamsLair/duality/issues/185) and making Duality Fonts full bitmap fonts.

**Comment by AdamsLair** [comment] 2015-08-07 20:08
This has been fixed in the course of the above mentioned issue. Closing this.

**Closed by AdamsLair** 2015-08-07 20:08 UTC
Labels: Bug, Engine, Usability
