### ISSUE TITLE
Write More Unit Tests

### ISSUE THREAD

**Issue by AdamsLair** [AdamsLair/duality#114] opened 2014-08-15 10:25 UTC
Duality already incorporates automated testing into its development and deployment cycle. However, these tests barely cover even half of Duality and while full coverage may not be necessary, a little bit more than now can't be too bad.

Testing Guidelines:

* **Minimize dependencies** of a single Test. The more things you rely on, the easier the test will break unconditionally due to core updates, and the more maintenance it requires.
* **Prefer custom Types** for testing generalized behavior. When testing Component logic, write a custom Test Component rather than using SpriteRenderer, etc.
* **Focus on fixed spec areas** when writing new tests. Don't test stuff that is in-development or about to change, as it will only increase maintenance for now. Tests should be focused on making sure that things remain in a working condition. Don't write a test, if that "working condition" isn't clearly defined yet.
* [Read this](http://www.adamslair.net/blog/?p=1463)

Things to think about how to test:

* Audio: Is there any way to "render to memory" with OpenAL, so Audio output can be tested? Especially tests for streaming would be great.
* Editor: Is there any way to test the user interface? Prior to this: Is there a good way to test editor functionality / logic without the user interface?

**Comment by WalliePL** [comment] 2015-01-25 11:07
Hi, i'm writing some test case for Rect class in Duality and I've reached to the problem.
If I use round method form MathF or Rect with something.5 (f.g 2.5) it is rounded to 2.0 - mathematically speaking it is a bug. However, I've found here : http://stackoverflow.com/questions/977796/why-does-math-round2-5-return-2-instead-of-3-in-c information about something called banker's rounding (now used in project) and rounding away from zero (which will round 2.5 to 3.0). Can You tell me which one we should expect from Duality if it want to round 2.5f?

**Comment by AdamsLair** [comment] 2015-01-25 13:12
Hi @WalliePL,

as `MathF` relies on `System.Math` for rounding, the same default behavior should be expected. However, I would suggest not to base unrelated unit tests on details like this and instead find a way to test things independently - like not using exact `.5f` values with implementation-dependent rounding, but instead using something like `.4f` where rounding behavior is non-ambiguous. :)

**Comment by WalliePL** [comment] 2015-02-07 20:58
Thank You for answer, i'll do this as You said. There is one more thing, I don't find any information about setting width and height of rect to value less than 0. Should it be possible to set those parameters less than zero? Everything was ok, till Intersects came for testing :). If width and height should be more than 0 then there is no validation for them.

**Comment by AdamsLair** [comment] 2015-02-07 23:15
> I don't find any information about setting width and height of rect to value less than 0. Should it be possible to set those parameters less than zero?

Width and Height are allowed to be less than zero, so having no check or enforcement there is fine :)

**Comment by AdamsLair** [comment] 2015-08-23 20:52
Bumping this as a reminder for myself to increase test coverage in the process of v2.0 implementation.

**Comment by ilexp** [comment] 2015-10-27 09:36
Closing this as part of a general cleanup, because it has grown way to unspecific. Testing shouldn't be an always-open issue, but a set of specific issues, a general best-practice and a tag for certain issues to reproduce them with a test before fixing / implement them.

**Closed by ilexp** 2015-10-27 09:36 UTC
Labels: Task
