### ISSUE TITLE
Profile / Reconsider Component Update Model

### ISSUE THREAD

**Issue by AdamsLair** [AdamsLair/duality#199] opened 2015-06-26 16:04 UTC
In its current implementation, Components are updated per GameObject:

- Update Object A
  - Update Transform A
  - Update RigidBody A
  - ...
- Update Object B
  - Update Transform B
  - Update RigidBody B
  - ...
- ...

In order to pave the way for cache optimizations, this could be changed to the following:

- Update Transforms
  - Update Transform A
  - Update Transform B
  - ...
- Update RigidBodies
  - Update RigidBody A
  - Update RigidBody B
  - ...

This could potentially lead better performance for highly used Components such as Transform or RigidBody - but before changing anything, this needs to be profiled. Preferably off-site for a first eval.

- The old update model.
- The new update model.
- An optimized version of the new model, where each Component class instance only refers to an index in an external struct[] data container.

**Comment by AdamsLair** [comment] 2015-06-27 11:53
First performance Tests reveal a completely negligible advantage of changing update order - less than a millisecond for 10000 objects over a course of 100 updates, i.e. around a nanosecond per object per frame. Closing this.

**Comment by BraveSirAndrew** [comment] 2015-07-02 08:45
I'm kinda surprised by the results here. Even writing a simple program outside of duality shows good performance speed ups for SOA architectures. This was also on my list of things to try (once Onikira is done) and in thinking about how to do it it seemed that the only real way would be to change components to basically be structures of arrays. Is that what you do in your test? Would love to see the code :)

**Comment by AdamsLair** [comment] 2015-07-02 09:43
> Is that what you do in your test?

Yes. (Assuming you meant the `struct[]` thing)

In fact, I would have expected a notable speedup myself and was a little disappointed by the results I got, and I'm not entirely sure why my tests don't show any notable speedup. I guess I expected the overhead of heap-objects all around memory, interfaces and virtual method calls to be higher.

One thing that does make a difference is when actually storing all test instances in an `object[]` and explicitly checking each one if it implements a certain interface - it's kind of an unrelated thing though, I added it mostly for reference to see the individual impact of `as` operations and `null` checks.

Here's the code:
https://www.dropbox.com/s/5gp6f6y3cnbaf6a/FastUpdatePerformanceTest.zip?dl=0

Let me know what you find.

**Comment by AdamsLair** [comment] 2015-07-05 15:17
Just to make sure I didn't miss something important here, and because I'm equally surprised by the results, [I asked StackOverflow on this](http://stackoverflow.com/questions/31231802/why-isnt-it-faster-to-update-a-struct-array-than-a-class-array). Maybe I made a dumb mistake, maybe there is some optimization going on - maybe someone can point me to it.

**Comment by AdamsLair** [comment] 2015-08-01 13:40
Re-Opened this with a new **ToDo:** Test this in an actual game Scene testbed with a huge (>10000) number of sprites and transforms and profile their Update time per frame.

**Comment by hsnabn** [comment] 2015-10-07 18:07
Um, it's been a long time since any updates on this issue, but in the StackOverflow question, the answer says that the negligible performance difference is probably because all the data needed to update already fits on the CPU cache.  
I think you can limit the CPU cache on virtual machines, so we could give it a go in a VM setup, if we needed to test it out?

**Comment by ilexp** [comment] 2015-10-08 12:53
>Um, it's been a long time since any updates on this issue, but in the StackOverflow question, the answer says that the negligible performance difference is probably because all the data needed to update already fits on the CPU cache.

Yup, I saw that. Had nothing to add here.

> I think you can limit the CPU cache on virtual machines, so we could give it a go in a VM setup, if we needed to test it out?

I don't think a VM test would really be a great deal of help here. Introducing artificial limitations will not necessarily tell us something about actual performance implications on real hardware, so the information we gain might be misleading or inconclusive. A real world test case with lots of objects might be more useful here, but in any case, this topic could use some more evaluation within Duality itself.

The issue is still unresolved, but non-critical. I'll just leave this open for future thoughts.

**Comment by ilexp** [comment] 2015-10-11 09:19
**Note:** One solid reason to at least update each Component type at a time is that it becomes trivial to measure the update and draw (collect) time of each Component type individually, without noticeable overhead.

**Comment by ilexp** [comment] 2015-10-11 12:29
**Progress:**
- Components are now updated sorted by their Type, so the same code path is executed over and over again before switching. 
  - Caching could later be improved further by allocating all Components of a certain Type in a row / introducing some kind of pooling mechanism for serialization, cloning, etc.
- Added per-Component-Type profile counters for update times each frame.

**Comment by ilexp** [comment] 2015-11-12 20:57
Closing this for now after recent progress and profiling. Revisit later.

**Closed by ilexp** 2015-11-12 20:57 UTC
Labels: Core, Performance, Task
