### ISSUE TITLE
New Project Dialog copies GamePlugin Files to "Empty Project"

### ISSUE THREAD

**Issue by SirePi** [AdamsLair/duality#166] opened 2015-02-20 08:37 UTC
If you create a New Empty project from an already existing project, all plugins present in Plugins directory will be copied over to the new one (including external and game plugin dlls)

I would expect it to contain only the basic Duality ones.

**Comment by AdamsLair** [comment] 2015-02-20 09:37
This is expected behavior. Duality doesn't distinguish between its own plugins and third-party plugins. An "empty project" will use all the plugins that the current one does.

One thing that is not expected is GamePlugins being copied as well. They should be filtered out.

**Comment by SirePi** [comment] 2015-02-20 10:15
Would it be possible to have a kind of project which is exactly a vanilla duality? maybe you can leverage the "download duality from nuget" magic that happens at first startup?

**Comment by AdamsLair** [comment] 2015-02-20 13:17
It's difficult. NuGet can't really help here, because it is an optional component of the system which can easily be deactivated by users who do not want to use Package Management at all. So relying on this is not possible.

Maybe a list of "vanilla" files could be generated at the first startup, but this would mean introducing another special case into the source for a single case that may or may not be useful. If you want a vanilla version of Duality, you can always keep one around, or just re-download it and I'd expect this to be the usual way to deal with a fresh install ^^

**Comment by SirePi** [comment] 2015-02-20 13:45
Fair enough :smile:

**Comment by RockyTV** [comment] 2015-06-06 14:09
I think this issue was fixed on the 2.0 master branch. I had written custom plugins in the main project, and created an empty project. The custom plugins were not copied to the new project.

**Comment by AdamsLair** [comment] 2015-06-06 14:32
Huh. I don't remember doing anything. Maybe it was just a side effect of something - will verify this, thanks!

**Comment by AdamsLair** [comment] 2015-09-03 16:41
**ToDo:** Verify the issue

**Comment by hsnabn** [comment] 2015-10-26 14:24
I tried this today, and it copied other plugins, along with XML documentation and PDBs into the new empty project directory.

One other thing I noticed: in the new empty project, in the CorePlugin source code directory, `bin` and `obj` directories are created, and are populated with files? I don't think this was intended behaviour. There was also a XML documentation file (`GamePlugin.core.xml`).

None of these files or directories were present in the old project from which I created the new empty project.

**Comment by ilexp** [comment] 2015-10-26 18:00
> One other thing I noticed: in the new empty project, in the CorePlugin source code directory, `bin` and `obj` directories are created, and are populated with files? I don't think this was intended behaviour. There was also a XML documentation file (`GamePlugin.core.xml`).

This should be normal - as part of the project creation, existing source code is compiled once. If no code is existing, the default code could end up being compiled, which would be an unwanted side-effect, but not harmful.

> I tried this today, and it copied other plugins, along with XML documentation and PDBs into the new empty project directory.

Okay, so this works as expected. Thanks for checking! I've tested it myself as well and can verify that both the creation of an Empty Project and cloning the existing one work without problems.

Closing this issue now. I'm not sure anymore what exactly this was about anyway :smile: Improving project creation in general is a valid ToDo, but that's one for a different issue.

**Closed by ilexp** 2015-10-26 18:00 UTC
Labels: Bug, Contribute Here, Difficulty: Easy, Editor

**Comment by hsnabn** [comment] 2015-10-26 18:11
Wait, game plugins are copied there too! That's the issue, isn't it?

**Comment by ilexp** [comment] 2015-10-26 18:19
> Wait, game plugins are copied there too! That's the issue, isn't it?

Just checked. They're actually the compiled version of a newly created game plugin. Which is the side-effect I mentioned. Since this is a pretty minor thing compared to the original question / issue (which has been cleared up), I'd close this one for now and revisit this later, should it come up again.

The "New Project" dialog is on my list of things to revisit anyway. I'm not happy with how it turned out in its current form and it's mostly a pre-"Package Management" relic.

**Comment by hsnabn** [comment] 2015-10-26 18:21
Hmm, I'm not sure I'm on the same page, but I'll leave it aside.
Here's an image I captured which will (hopefully) clear any miscommunication:
http://i.imgur.com/GfgQMtb.png

**Comment by ilexp** [comment] 2015-10-26 18:27
> Hmm, I'm not sure I'm on the same page, but I'll leave it aside.
Here's an image I captured which will (hopefully) clear any miscommunication:
http://i.imgur.com/GfgQMtb.png

Yep, that's what SirePi reported initially. :smile: Here's my answer on this:

> This is expected behavior. Duality doesn't distinguish between its own plugins and third-party plugins. An "empty project" will use all the plugins that the current one does.

So what you're seeing is not a bug, but expected behavior. It is how the "New Project" dialog works and, if you will, one of its conceptual flaws.

I've created a new issue with regard to the "New Project" dialog [here](https://github.com/AdamsLair/duality/issues/235) - it doesn't have that bug report structure, but is now aimed at dealing with the problem on a more general level.

**Comment by hsnabn** [comment] 2015-10-26 18:33
I think the problem here is that the Empty Project option results in something the exact opposite: a project that has already been populated.
But nevertheless, I'll let it go (stumbled upon this issue while browsing, never expected to get this far). It just might be because I'm not understanding what's going on, but any further discussion can take place in the new issue, if need be.

**Comment by ilexp** [comment] 2015-10-26 19:05
> I think the problem here is that the Empty Project option results in something the exact opposite: a project that has already been populated.

I see the problem here, but the existing "New Project" dialog simply can't do anything about it that wouldn't result in a hack, code-wise. I completely agree that this behavior may be counter-intuitive. (To be fair, all data is correctly stripped away as expected, all settings are reset, etc., but still)

I'm not saying what you're observing is wrong or not worth fixing, but that fixing it in the context of the existing code would not do the project a favor - hence the new issue with a focus on rethinking and revisiting the "New Project" dialog as a whole.

**Comment by hsnabn** [comment] 2015-10-26 19:14
Ah yes, I think I understand it now. The dialog is getting an overhaul.
Thanks for explaining.

**Comment by ilexp** [comment] 2015-10-26 19:21
> Ah yes, I think I understand it now. The dialog is getting an overhaul, or is getting remade.
Thanks for explaining.

Yes - either an overhaul (eventually), or a much simpler replacement. Maybe an actual "New Project" dialog isn't even needed anymore - we'll see. :) The discussion and concept work on this will be in the [new issue](https://github.com/AdamsLair/duality/issues/235).
