### ISSUE TITLE
Error Updating Packages

### ISSUE THREAD

**Issue by BobGneu** [AdamsLair/duality#624] opened 2018-02-06 06:11 UTC
### Summary

Today I attempted to install the latest packages to upgrade my environment. I went to `File` > `Manage Packages` changed my `View` to `Online Repository` and updated both `Duality.Editor` and `Duality.Core`. The updater ran and I was prompted to apply the changes, which restarted the editor. 

Once it returned I resumed installing packages and now every package provides the same error notice: 

![image](https://user-images.githubusercontent.com/857751/35844124-c212cfec-0ac0-11e8-85bf-82af525066a3.png)

### How to reproduce [Bugs]

- `File` > `Manage Packages`
- Update `View` to `Online Repository`
- Update to latest `Duality.Editor` and `Duality.Core`
- Apply updates
- Return to `File` > `Manage Packages`
- Update `View` to `Online Repository`
- Attempt to install any package. 

### Workaround [Bugs]

- Manually update to latest files from download link on site. 

### Attachments

Error In Context: ![image](https://user-images.githubusercontent.com/857751/35844210-33400310-0ac1-11e8-8f6d-8ae86f782621.png)

Log file: [logfile_editor.txt](https://github.com/AdamsLair/duality/files/1697936/logfile_editor.txt)

**Comment by ilexp** [comment] 2018-02-06 16:23
I can't reproduce this from a fresh install. Looking at the logfile, it seems that there are one or more libraries or plugins that attempt to resolve API that was only introduced in the `develop-3.0` branch, which isn't released yet. Is it possible that you mixed custom-built v3.0 libraries with downloaded ones from the package manager?

**Comment by BobGneu** [comment] 2018-02-08 04:30
I may have. Will upload shortly.

**Comment by BobGneu** [comment] 2018-02-08 17:05
Just realized that I overwrote my files when I was trying to sort out the workaround. 
I no longer have this issue. Not sure if the screenshots are going to help. 

Here is the screenshot of my Source/Packages directory
![image](https://user-images.githubusercontent.com/857751/35986881-23172e06-0caf-11e8-99ed-763843367f0e.png)

```xml
<?xml version="1.0" encoding="utf-8"?>
<PackageConfig>
  <RepositoryUrl>https://packages.nuget.org/api/v2</RepositoryUrl>
  <Packages>
    <Package id="AdamsLair.Duality" version="2.14.8.0" />
    <Package id="AdamsLair.Duality.Launcher" version="2.3.4.0" />
    <Package id="AdamsLair.Duality.Backend.DotNetFramework" version="2.1.1.0" />
    <Package id="AdamsLair.Duality.Plugins.Compatibility" version="2.0.2.0" />
    <Package id="AdamsLair.Duality.Docs" version="2.0.1.0" />
    <Package id="AdamsLair.Duality.Backend.DefaultOpenTK" version="2.0.21.0" />
    <Package id="AdamsLair.Duality.Editor" version="2.10.9.0" />
    <Package id="AdamsLair.Duality.Editor.Plugins.Base" version="2.2.13.0" />
    <Package id="AdamsLair.Duality.Editor.Plugins.CamView" version="2.6.3.0" />
    <Package id="AdamsLair.Duality.Editor.Plugins.HelpAdvisor" version="2.0.6.0" />
    <Package id="AdamsLair.Duality.Editor.Plugins.LogView" version="2.1.10.0" />
    <Package id="AdamsLair.Duality.Editor.Plugins.ObjectInspector" version="2.1.2.0" />
    <Package id="AdamsLair.Duality.Editor.Plugins.ProjectView" version="2.0.14.0" />
    <Package id="AdamsLair.Duality.Editor.Plugins.SceneView" version="2.0.14.0" />
    <Package id="AdamsLair.Duality.Editor.Plugins.PackageManagerFrontend" version="2.1.3.0" />
    <Package id="AdamsLair.Duality.Editor.Backend.DefaultOpenTK" version="2.0.7.0" />
    <Package id="SnowyPeak.Duality.Plugins.YAUI.Core" version="2.0.0.0" />
  </Packages>
</PackageConfig>
```

**Comment by ilexp** [comment] 2018-02-08 20:16
> > Is it possible that you accidentally mixed custom-built v3.0 libraries with downloaded ones from the package manager, for example by using the same build folder?

> I may have. Will upload shortly.

> Just realized that I overwrote my files when I was trying to sort out the workaround.
I no longer have this issue.

Probably a custom v3.0 / released v2.x issue then 🙂 Thanks for the screenshots though! Look unsuspicious so far, which would be expected if it was the build folder mixup. Closing this.

**Closed by ilexp** 2018-02-08 20:16 UTC
