### ISSUE TITLE
Editor Crash while panning the camera on the scene view

### ISSUE THREAD

**Issue by raizam** [AdamsLair/duality#268] opened 2016-01-18 12:03 UTC
Hi,

Using the latest version of duality, a crash occurs when panning the camera with the mouse middle button, and then pointing the mouse out of the scene view while the scene view was still panning.

not sure I could make myself clear, but it is very easy to reproduce

**Comment by ilexp** [comment] 2016-01-18 19:37
I can't reproduce this bug based on your description.

1. What do you mean by "latest version"? Binary release or built from the latest master branch source code?
2. Can you reproduce this bug in a fresh Duality build / install? How exactly? Are there details we might not be aware of?
3. What do you mean by crash?
4. Is there a logfile_editor.txt after the crash? Can you upload it somewhere?
5. If you use a binary release, can you provide your `PackageConfig.xml` file?

**Comment by raizam** [comment] 2016-01-18 22:35
1.  Latest version is the binary version I downloaded on the website yesterday.
2.  On the scene view, pushing the middle mouse button to pan the camera towards a direction, producing a "throwing" like feel. If the pan move isn't complete, and the mouse cursor points out of the sceneview panel, pointing to any toolbar widget, then a Windows crash reports appear.
3 regular windows crash dialog
4 the logfile_editor.txt doesn't contain any exception
5 here is my packageConfig.xml
<?xml version="1.0" encoding="utf-8"?>
<PackageConfig>
  <RepositoryUrl>https://packages.nuget.org/api/v2</RepositoryUrl>
  <Packages>
    <Package id="AdamsLair.Duality" version="2.2.0.0" />
    <Package id="AdamsLair.Duality.Launcher" version="2.0.1.0" />
    <Package id="AdamsLair.Duality.Backend.DotNetFramework" version="2.0.0.0" />
    <Package id="AdamsLair.Duality.Plugins.Compatibility" version="2.0.0.0" />
    <Package id="AdamsLair.Duality.Docs" version="2.0.0.0" />
    <Package id="AdamsLair.Duality.Backend.DefaultOpenTK" version="2.0.4.0" />
    <Package id="AdamsLair.Duality.Editor" version="2.2.0.0" />
    <Package id="AdamsLair.Duality.Editor.Plugins.Base" version="2.1.0.0" />
    <Package id="AdamsLair.Duality.Editor.Plugins.CamView" version="2.2.0.0" />
    <Package id="AdamsLair.Duality.Editor.Plugins.HelpAdvisor" version="2.0.0.0" />
    <Package id="AdamsLair.Duality.Editor.Plugins.LogView" version="2.0.0.0" />
    <Package id="AdamsLair.Duality.Editor.Plugins.ObjectInspector" version="2.0.0.0" />
    <Package id="AdamsLair.Duality.Editor.Plugins.ProjectView" version="2.0.2.0" />
    <Package id="AdamsLair.Duality.Editor.Plugins.SceneView" version="2.0.1.0" />
    <Package id="AdamsLair.Duality.Editor.Plugins.PackageManagerFrontend" version="2.0.0.0" />
    <Package id="AdamsLair.Duality.Editor.Backend.DefaultOpenTK" version="2.0.1.0" />
  </Packages>
</PackageConfig>

**Comment by raizam** [comment] 2016-01-18 23:17
I finally forked the repository, compiled the source, and reproduced the issue with visual studio debugger attached.

		An unhandled exception of type 'System.AccessViolationException' occurred in OpenTK.dll

		Additional information: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.


here is the stacktrace:

		   at OpenTK.Platform.Windows.Functions.SwapBuffers(IntPtr dc)
		   at OpenTK.Platform.Windows.WinGLContext.SwapBuffers()
		   at Duality.Editor.Backend.DefaultOpenTK.NativeEditorGraphicsContext.Duality.Editor.Backend.INativeEditorGraphicsContext.PerformBufferSwap()
		   at Duality.Editor.DualityEditorApp.PerformBufferSwap() in D:\indie\duality\DualityEditor\DualityEditorApp.cs:line 648
		   at Duality.Editor.DualityEditorApp.Application_Idle(Object sender, EventArgs e) in D:\indie\duality\DualityEditor\DualityEditorApp.cs:line 1365
		   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
		   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
		   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
		   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
		   at Duality.Editor.Program.Main(String[] args) in D:\indie\duality\DualityEditor\Program.cs:line 102
		   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
		   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
		   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
		   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
		   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
		   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
		   at System.Threading.ThreadHelper.ThreadStart()

**Comment by ilexp** [comment] 2016-01-19 20:38
> On the scene view, pushing the middle mouse button to pan the camera towards a direction, producing a "throwing" like feel. If the pan move isn't complete, and the mouse cursor points out of the sceneview panel, pointing to any toolbar widget, then a Windows crash reports appear.

Hmm.. as far as I can tell, this is exactly what I did too. Works fine on my testing machine :| A Windows crash report is also a bit unusual for a managed application, seems like something might be wrong on a lower level interface.

> An unhandled exception of type 'System.AccessViolationException' occurred in OpenTK.dll 

> here is the stacktrace:
>
> 		   at OpenTK.Platform.Windows.Functions.SwapBuffers(IntPtr dc)
>		   at OpenTK.Platform.Windows.WinGLContext.SwapBuffers()
>		   at Duality.Editor.Backend.DefaultOpenTK.NativeEditorGraphicsContext.Duality.Editor.Backend.INativeEditorGraphicsContext.PerformBufferSwap()
>		   at Duality.Editor.DualityEditorApp.PerformBufferSwap() in D:\indie\duality\DualityEditor\DualityEditorApp.cs:line 648

And that's probably it. Something goes wrong while trying to render the game. Probably a driver-, hardware- or OS dependent bug. Thanks for doing a manual build from source to debug this, you really got a valuable piece of information there.

That said, a full upload of your `logfile_editor.txt` would be helpful. Not (necessarily) because it might contain an exception, but because I can see the last log entry that was apparently fine, as well as a lot of diagnostic information that would be a lot more tedious to ask bit by bit. Can you upload one after reproducing the crash?

Meanwhile, checking the usual:
- Are you video card drivers up-to-date, or does updating them change anything in behavior?
- Do you have any custom video driver overrides active, such as enabling or disabling certain settings in the Nvidia Control Panel (or similar)?

**Comment by raizam** [comment] 2016-01-20 11:30
I've updated the nvidia drivers, but the behavior is still here. I'm using a windows 7 64 laptop.
What's interesting is that if I wait the drag behavior to end, the problem doesn't occur.

I don't know much about the inner workings of the editor, but the first thing that came in mind was a problem related to Winforms/STAThread issue, where an operation is not executed on the main thread. Just an idea.

**Comment by raizam** [comment] 2016-01-20 14:13
here is the logfile_editor.txt

		[Core] Msg: Using 'DefaultPluginLoader' to load plugins.
		[Core] Msg: Scanning for core plugins...
		[Core] Msg:   Plugins\Compatibility.core.dll...
		[Core] Msg:     Assembly loaded: Compatibility.core
		[Core] Msg:     Assembly loaded: System.Linq.Expressions
		[Core] Msg:     Assembly loaded: Anonymously Hosted DynamicMethods Assembly
		[Core] Msg:   Plugins\DefaultOpenTKBackend.core.dll...
		[Core] Msg:     Assembly loaded: DefaultOpenTKBackend.core
		[Core] Msg:     Assembly loaded: OpenTK
		[Core] Msg:   Plugins\DotNetFrameworkBackend.core.dll...
		[Core] Msg:     Assembly loaded: DotNetFrameworkBackend.core
		[Core] Msg:   Plugins\DynamicLighting.core.dll...
		[Core] Msg:     Assembly loaded: DynamicLighting.core
		[Core] Msg:   Plugins\Steering.core.dll...
		[Core] Msg:     Assembly loaded: Steering.core
		[Core] Msg: Loading auxiliary libraries...
		[Core] Msg:   Assembly loaded: OpenTK.GLControl
		[Core] Msg: Initializing ISystemBackend...
		[Core] Msg:   .Net Framework...
		[Core] Msg:     Operating System: Microsoft Windows NT 6.1.7601 Service Pack 1 (Windows 7)
						64 Bit Process: True
						CLR Version: 4.0.30319.42000
						Processor Count: 4
		[Core] Msg: Assembly loaded: System.Text.RegularExpressions
		[Core] Msg: Initializing IGraphicsBackend...
		[Core] Msg:   OpenGL 2.1 (OpenTK)...
		[Core] Msg:     Initializing OpenTK...
		[Core] Msg:       Backend: PreferNative
						  EnableHighResolution: False
		[Core] Msg: Initializing IAudioBackend...
		[Core] Msg:   OpenAL (OpenTK)...
		[Core] Msg:     OpenAL Drivers not found. Using 64 Bit software fallback.
		[Core] Msg:     Available devices:
						Speakers (Realtek High Definition Audio) (Default)
		[Core] Msg:     Current device: OpenAL Soft
		[Core] Msg:     OpenAL Version: 1.1 ALSOFT 1.15.1
						Vendor: OpenAL Community
						Renderer: OpenAL Soft
						Effects: True
		[Core] Msg:     256 sources available
		[Core] Msg: Initializing core plugins...
		[Core] Msg:   Compatibility.core...
		[Edit] Msg:     Analyzing Core Plugin: Compatibility.core
		[Core] Msg:   DefaultOpenTKBackend.core...
		[Edit] Msg:     Analyzing Core Plugin: DefaultOpenTKBackend.core
		[Core] Msg:   DotNetFrameworkBackend.core...
		[Edit] Msg:     Analyzing Core Plugin: DotNetFrameworkBackend.core
		[Core] Msg:   DynamicLighting.core...
		[Edit] Msg:     Analyzing Core Plugin: DynamicLighting.core
		[Core] Msg:   Steering.core...
		[Edit] Msg:     Analyzing Core Plugin: Steering.core
		[Core] Msg: DualityApp initialized
					Debug Mode: True
					Command line arguments: null
		[Edit] Msg: Scanning for editor plugins...
		[Edit] Msg:   Loading 'Plugins\CamView.editor.dll'...
		[Core] Msg:     Assembly loaded: CamView.editor
		[Edit] Msg:   Loading 'Plugins\DefaultOpenTKBackend.editor.dll'...
		[Core] Msg:     Assembly loaded: DefaultOpenTKBackend.editor
		[Edit] Msg:   Loading 'Plugins\DynamicLighting.editor.dll'...
		[Core] Msg:     Assembly loaded: DynamicLighting.editor
		[Edit] Msg:   Loading 'Plugins\EditorBase.editor.dll'...
		[Core] Msg:     Assembly loaded: EditorBase.editor
		[Core] Msg:     Assembly loaded: PopupControl
		[Edit] Msg:   Loading 'Plugins\HelpAdvisor.editor.dll'...
		[Core] Msg:     Assembly loaded: HelpAdvisor.editor
		[Edit] Msg:   Loading 'Plugins\LogView.editor.dll'...
		[Core] Msg:     Assembly loaded: LogView.editor
		[Edit] Msg:   Loading 'Plugins\ObjectInspector.editor.dll'...
		[Core] Msg:     Assembly loaded: ObjectInspector.editor
		[Edit] Msg:   Loading 'Plugins\PackageManagerFrontend.editor.dll'...
		[Core] Msg:     Assembly loaded: PackageManagerFrontend.editor
		[Core] Msg:     Assembly loaded: Aga.Controls
		[Edit] Msg:   Loading 'Plugins\ProjectView.editor.dll'...
		[Core] Msg:     Assembly loaded: ProjectView.editor
		[Edit] Msg:   Loading 'Plugins\SceneView.editor.dll'...
		[Core] Msg:     Assembly loaded: SceneView.editor
		[Core] Msg: Initializing IEditorGraphicsBackend...
		[Core] Msg:   GLControl (OpenTK)...
		[Core] Msg: Initializing default content...
		[Core] Msg:   Assembly loaded: System.Runtime.InteropServices
		[Core] Msg:   Assembly loaded: System.Reflection.Extensions
		[Core] Msg:   Assembly loaded: System.Collections.Concurrent
		[Core] Msg:   Assembly loaded: System.Threading.Tasks.Parallel
		[Core] Msg:   Assembly loaded: System.Xml.ReaderWriter
		[Core] Msg:   Assembly loaded: System.Text.Encoding
		[Core] Msg:   Assembly loaded: NVorbis
		[Core] Msg:   ...done!
		[Edit] Msg: Loading user data...
		[Edit] Msg:   Loading DockPanel data...
		[Edit] Msg:     Deserializing layout: 'Duality.Editor.Plugins.CamView.CamView'
		[Edit] Msg:     Deserializing layout: 'Duality.Editor.Plugins.ProjectView.ProjectFolderView'
		[Edit] Msg:     Deserializing layout: 'Duality.Editor.Plugins.SceneView.SceneView'
		[Edit] Msg:     Deserializing layout: 'Duality.Editor.Plugins.ObjectInspector.ObjectInspector'
		[Edit] Msg:     Deserializing layout: 'Duality.Editor.Plugins.HelpAdvisor.HelpAdvisor'
		[Edit] Msg:     Deserializing layout: 'Duality.Editor.Plugins.LogView.LogView'
		[Edit] Msg:   Loading editor user data...
		[Edit] Msg: Initializing editor plugins...
		[Edit] Msg:   CamView...
		[Edit] Msg:   DefaultOpenTKEditorBackend...
		[Edit] Msg:   DynamicLighting...
		[Edit] Msg:   EditorBase...
		[Edit] Msg:   HelpAdvisor...
		[Edit] Msg:   LogView...
		[Edit] Msg:   ObjectInspector...
		[Edit] Msg:   PackageManagerFrontend...
		[Edit] Msg:   ProjectView...
		[Edit] Msg:   SceneView...
		[Core] Msg: Assembly loaded: FarseerDuality
		[Core] Msg: Assembly loaded: Accessibility

**Comment by ilexp** [comment] 2016-01-20 18:37
> here is the logfile_editor.txt

Thanks!

> What's interesting is that if I wait the drag behavior to end, the problem doesn't occur.

The CamView only re-renders the Scene when either the Scene or the view on it have changed. After the drag behavior ends, no redraw occurs except when triggered. So.. it's not really about the panning itself, but rendering simply doesn't occur otherwise while outside the CamView. I'm not exactly sure what's the matter here.

When the sandbox mode is active, rendering occurs each update step. What happens when you run the sandbox in the editor? Does this work? Does it make a difference where your cursor is?

> I don't know much about the inner workings of the editor, but the first thing that came in mind was a problem related to Winforms/STAThread issue, where an operation is not executed on the main thread. Just an idea.

I'm not doing a lot of multi-threading in engine and editor, and rendering in particular is always done on the main thread. I don't know a lot about the STAThread issue you mentioned - can you provide some background for me?

**Comment by raizam** [comment] 2016-01-22 23:44
Ok the problem is fixed :-D
The editor is also running much faster now.

Your first intuitions were right, it was related to NVidia configuration, all I did is to restore the default settings. What's strange is that I actualy never changed anything in there.

I'm very happy this is fixed, I can now evaluate Duality more properly :)

**Comment by ilexp** [comment] 2016-01-22 23:47
Ah, that's great to hear :) Allright then, closing this!

**Closed by ilexp** 2016-01-22 23:47 UTC
Labels: Bug, Editor

**Comment by raizam** [comment] 2016-01-22 23:49
also, you should come to the IRC channel more often, with @RockyTV we feel lonely =)

**Comment by ilexp** [comment] 2016-01-23 10:23
I'll try to show up once in a while, real life just keeps me busy a lot lately :)
