### ISSUE TITLE
Tilemap overides filter method

### ISSUE THREAD

**Issue by skrrtskrrtman** [AdamsLair/duality#766] opened 2019-12-02 11:49 UTC
### Summary

Tilemaps will always use linear texture filtering despite nearest being used in the texture file as seen here.
![linear filtering tilemap](https://user-images.githubusercontent.com/50763036/69957051-ba894200-153c-11ea-9996-cd766543f3c4.PNG)
![DualityEditor_CjjiWUXYMl](https://user-images.githubusercontent.com/50763036/69957062-bf4df600-153c-11ea-8a4a-1b7aede1cdb3.png)

### How to reproduce

- create texture with linear filtering
- create tile map from previously mentioned texture 
- paint something in the scene with the tilemap 
- zoom in on painted area in scene view

**Comment by ilexp** [comment] 2019-12-15 09:05
Can't reproduce this here.

I _think_ you may have got the wrong spot to specify this behavior. For tilemaps, you don't need a Texture at all, just the Pixmap - all required Textures are created internally in the Tileset (to account for generated AutoTiles), and not exposed through editor UI. You can adjust their desired settings in the Tileset when selecting the layer:

![DualityEditor_cOVcgZo2NC](https://user-images.githubusercontent.com/14859411/70860469-5f832200-1f22-11ea-9969-67b0980b0c35.png)
![explorer_pfPmM226gY](https://user-images.githubusercontent.com/14859411/70860470-61e57c00-1f22-11ea-8bdd-02530bb27f26.png)

Closing this for now, but let me know if I misunderstood the issue and we'll re-open it.

**Closed by ilexp** 2019-12-15 09:05 UTC
