### ISSUE TITLE
DataObject Ref vs. Clone Data Formats

### ISSUE THREAD

**Issue by deanljohnson** [AdamsLair/duality#655] opened 2018-05-12 14:08 UTC
### Summary

While working on #652 we ran into an issue where copy/paste and usages of DataObject do not always agree in how stored objects should be treated (clones vs references). Investigate possible fixes to this problem.

### Details

Objects/Components/ContentRefs are currently stored in a DataObject for drag/drop, copy/paste, etc., operations. When placed into a DataObject, data is assigned a format. Currently, that format only describes the type of the data. This creates problems when a DataObject is used to hold both clones of data and references to data as those two are not equivalent but will have the same type string.

A possible solution to this would be to expand ExtMethodsDataObject to allows storing both a cloned format and a reference format. Calling code would then specify which one it was placing into the DataObject when calling SetWrappedData or on the helper methods such as SetGameObjectRefs. To make things easier on the receiving side of a DataObject, requesting a cloned format could automatically perform a deep clone of reference formatted data if a cloned format is not available. Creating a DataObject would now entail two method calls - one for cloned data and one for reference data - or we could provide a flag on the SetReferenceData method that automatically performs the DeepClone.

In general, the ExtMethodsDataObject code could use some cleanup. One thing we may be able to do is reduce the public set of methods presented in this code as the SetWrappedData/GetWrappedData/GetWrappedDataPresent methods are almost entirely used from other code in this file. The only exceptions are VectorPropertyEditor and ConversionData which both make use of those methods. The solution of using a separate data format for clones vs references will make those method signatures noisier and so it might be better to first remove their usage in outside code somehow. It seems like it may be nice to remove the current GetXPresent/Contains in place of TryGetX methods (like .Net has on Dictionary) instead as the GetX/Contains methods are doing full fetches of the data in the current implementation which could be costly.

@ilexp other issues with ExtMethodsDataObject that you see?

### TODO:
- Determine if we can reduce the public API of ExtMethodsDataObject
- Refactor and cleanup ExtMethodsDataObject where possible
- Implement new wrapper prefixes and/or replace current (current "SerializableWrapper:")
- Implement new clone format methods, paying careful attention to code reuse as this could grow out of control fairly quickly. Perhaps a new format flag to existing method signatures?
- Implement auto-conversion to clone formats from reference format on receiving end of DataObjects
- Test, test, test, as this code is used in quite a few places

**Comment by ilexp** [comment] 2018-05-12 15:52
Nice writeup, thanks!

> Objects/Components/ContentRefs are currently stored in a DataObject for drag/drop, copy/paste, etc., operations.

We can ignore ContentRefs here due to their serializable, ID-based design. From the perspective of DataObject and Clipboard, they're no different than a vector, color, or any other by-value data type.

> To make things easier on the receiving side of a DataObject, requesting a cloned format could automatically perform a deep clone of reference formatted data if a cloned format is not available.

👍 

> It seems like it may be nice to remove the current GetXPresent/Contains in place of TryGetX methods (like .Net has on Dictionary) instead

Neat, I like that idea. The original API was built around what `DataObject` itself provides, but a `Set` / `TryGet` solution would be much more elegant. We could consider providing a similar API surface even for the builtin data types (files, text, etc.) we use.

> One thing we may be able to do is reduce the public set of methods presented in this code as the SetWrappedData/GetWrappedData/GetWrappedDataPresent methods are almost entirely used from other code in this file.

I would actually regard them as the main API here, with most other methods just being higher-level convenience methods for more specific use cases. We might find a better naming or API for the same base functionality though, I imagine this could be cleaned up a lot with the `TryGet` approach and maybe some polishing.

Overall, I think we should also consider a different terminology than "reference" and "cloned". Cloned is derived from a use case we happened to run across, and I'm not sure it translates well into the whole DataObject / Clipboard world. Since they're all about passing data around between unknown parties, how about we make the distinction between serializing a reference and serializing an object instead? Serializing an object implies that the result is a copy, serializing a reference implies that the result is the original.

**Comment by deanljohnson** [comment] 2018-05-12 19:01
> Overall, I think we should also consider a different terminology than "reference" and "cloned". Cloned is derived from a use case we happened to run across, and I'm not sure it translates well into the whole DataObject / Clipboard world. Since they're all about passing data around between unknown parties, how about we make the distinction between serializing a reference and serializing an object instead? Serializing an object implies that the result is a copy, serializing a reference implies that the result is the original.

I agree - I didn't like cloned either but it was the best I had to describe it at the time of the write-up. I'm actually using Value and Reference in the implementation I'm working on. 

The Value format of a reference type is what you would get from DeepCloning that reference typed object. Value ypes such as Vector3 are only being put into the DataObject in Value format and you cannot get them from the DataObject in Reference format.

**Comment by deanljohnson** [comment] 2018-05-12 19:48
I've begun work on this [here](https://github.com/deanljohnson/duality/tree/data-object-formats).

Regarding the TryGetX methods, I don't think they are warranted on the GetWrappedData methods - those are efficient as they are. I'll implement them for things like GetGameObjectRefs because ContainsGameObjectRefs alreadys gets the data (which may lead to a conversion and could be fairly expensive). Having a TryGetX method would avoid the duplicate GetWrappedData call and possibly duplicate conversion.

Moving forward I want to add a DataFormat parameter to [methods like this](https://github.com/deanljohnson/duality/blob/45474f702970bd4811019d1b0db32627f81d55e0/Source/Editor/DualityEditor/Utility/Extensions/ExtMethodsDataObject.cs#L162-L174) and removes the "refs" from their name. Whether data is stored in Reference format or Value format will depend on the parameter.

I'm not sure if I understand all the use cases of ConversionData so I was wondering if I could get some feedback on [this bit of code](https://github.com/deanljohnson/duality/blob/45474f702970bd4811019d1b0db32627f81d55e0/Source/Editor/DualityEditor/Extensibility/DataConversion/ConversionData.cs#L34-L64). I have it checking/getting reference formatted data which should match the previous implementation. However, if only Value formatted data exists in the DataObject, uses of ConversionData would fail. Should ConversionData check for both cases, maybe preferring reference data if available? Or should ConversionData take an additional parameter in it's constructor that decides which format to use?

**Comment by deanljohnson** [comment] 2018-05-13 04:39
Ran into a bit of a speed bump when dealing with collection types and implementing automatic Value format conversion from Reference formatted data. Within the context of GetGameObjects, GetComponents, etc., there is no issue as the target type is strongly typed and doesn't need reflection so I can easily walk the array and DeepClone the items.

However, GetWrappedData simply returns an object. I can check if the object retrieved from the DataObject implements IEnumerable and then walk through the enumeration and DeepClone the elements, but there are two problems I have yet to solve:
1. What collection type do I output? In the overload that accepts a type parameter I may be able to handle this with quite a bit of reflection, but with the overload that only takes a string parameter for format I have no information on the collection type to output.
2. I also need to return a collection of the right element type as the caller of this method should not have to convert an object[] to a TargetType[] when they asked for a TargetType[].

We could solve this by saying that Get/SetWrappedData do not support automatic Ref->Value conversion for collection types. The Get/SetGameObjects and similar methods could then handle the conversion themselves as needed. With the set of Get/SetX methods implemented, there should be very few calls that need to manually convert object[] to TargetType[] (actually, I think all the current calls can be done without this).

It should also be possible to implement a Get/SetWrappedDataArray methods that explicitly return object[] and leave conversion to target collection types up to the caller.

**Comment by deanljohnson** [comment] 2018-05-13 06:25
### Progress
- Simplified existing code and extracted reusable bits
- Added DataFormat parameters to many of the DataObject extensions methods to select between storing References or Values.
- All GetX extension methods now return null on error, rather than having some which would return empty collections and some null.
- Added a few unit tests for these extension methods and their new DataFormat parameters
- Added TryGet methods for Components and GameObjects as a performance optimization and changed many usages throughout the code base of the Contains/Get pair to use TryGet instead. The component method is where this really benefits as the ContainsComponents must do a full get of the data. That coupled with the automatic DeepCloning which may occur makes the ContainsComponents call fairly expensive.
- Implemented automatic conversion from Reference formatted data to Value formatted data. Works for stored collection objects only if done through GetGameObjects and GetComponents. GetWrappedData is not able to deep clone elements of arbitrary collections. Non-collection objects can still be converted when using GetWrappedData.

### ToDo
- Add TryGet methods for IColorData, BatchInfo, ContentRefs, and strings. Gives a minor performance benefit and maintains consistency with GameObject and Component methods.
- More testing. Up until this point I've mainly focused on GameObjects and Component and so the other methods are not well tested.
- Write more unit tests
- Consider whether or not Value formatted data should be cloned immediately upon being put into the DataObject. To keep things consistent, adding Reference formatted data would have to automatically add Value formatted data if cloning was done up-front on Value data. As of now I think the best course is to NOT clone up-front and instead rely the setting code to add Value formatted data if it needs to.
- Consider writing TryGetWrappedData methods. I have a feeling that the method signature and necessary overloads will get fairly messy and make it not worth it, but still warrants investigation.

**Comment by ilexp** [comment] 2018-05-13 08:39
> Should ConversionData check for both cases, maybe preferring reference data if available? Or should ConversionData take an additional parameter in it's constructor that decides which format to use?

It should try both, in order of priority (refs first, values next).

> I think I want to look into writing unit tests for this stuff - need to make sure the automated conversion stuff works and that everything behaves as expected whether or not serialization happens (Clipboard).

Great idea, and good opportunity to write some 👍 

> Ran into a bit of a speed bump when dealing with collection types and implementing automatic Value format conversion from Reference formatted data. Within the context of GetGameObjects, GetComponents, etc., there is no issue as the target type is strongly typed and doesn't need reflection so I can easily walk the array and DeepClone the items.
>
> However, GetWrappedData simply returns an object. I can check if the object retrieved from the DataObject implements IEnumerable and then walk through the enumeration and DeepClone the elements, but there are two problems I have yet to solve:

So if I understand it correctly, the problem is that for an `object` parameter, you don't know how to safely apply `DeepClone` in order to produce a "serialized object" value from a "serialized reference" value?

If that's the case, I don't think you need to look into the object at all, even for the GameObject or Component case. Just `DeepClone` the wrapped root object, regardless of what it is. `DeepClone` is not limited to GameObjects or Components, it can operate on any object: If it happened to be a `GameObject[]`, you'll get a new `GameObject[]` with the cloned instances. If it was a `Dictionary<string,Foo<Bar>>`, you'll get a clone of that entire object graph, and so on.

**Comment by deanljohnson** [comment] 2018-05-13 16:45
Are you sure cloning a collection will clone the elements? I tried and the
objects were still reference equal to the originals. I’ll take another look.

**Comment by deanljohnson** [comment] 2018-05-13 17:08
So here is a simple test case that fails and doesn't use anything related to DataObject:

```
GameObject[] arr = new [] {gameObject};
Assert.IsFalse(ReferenceEquals(gameObject, arr.DeepClone()[0]));
```

This assertion will fail. The DeepClone call is not cloning the elements of the array, just creating a new array with the same elements. This is the crux of the problem I was having with the collections.

**Comment by ilexp** [comment] 2018-05-13 17:37
Ah, you're right. It's not actually a collection problem, but I did overlook that one: GameObject and Components are configured in a way to default to be treated as reference only, unless cloned directly. So when cloning a GameObject, it's cloned, but when cloning something else and encountering a GameObject, it's treated as a reference unless specified otherwise. Unfortunately, specifying something else is only possible for field definitions, not "for this cloning call", but I'm not entirely sure this would be the "right" solution here anyway.

So, how about we adjust wrappers and API instead to accommodate for a collection of objects as a top-level construct? That way, the API would accept an `IEnumerable<object>` instead of an `object`, and you could clone each item separately, thus enforcing the full clone of them. 

As a bonus, the `SerializableReferenceWrapper` would define one ID per actual object, not per array of objects, which would enable ID reuse for objects that are already in the reference map.

**Comment by deanljohnson** [comment] 2018-05-14 00:33
Your idea of changing the API to `IEnumerable<object>` rather than object seems to be working. I still have to do work with types other than GameObject/Components (working on it now), but nothing is broken yet lol.

While I was working on BatchInfo a question came up and I was wondering if you could answer it. Is there a reason why the BatchInfoPropertyEditor doesn't use GetBatchInfo's [here](https://github.com/deanljohnson/duality/blob/e86282f82ff14a17f65d90570780a24ffc86dd79/Source/Plugins/EditorBase/PropertyEditors/BatchInfoPropertyEditor.cs#L773-L785)? It ends up making the same calls that GetBatchInfo would, but has to go through the ConvertOperation call chain first. Even if there is a case where GetBatchInfo would fail (because there wasn't BatchInfo directly in the DataObject, just something convertible to BatchInfo) it could probably still be beneficial to first check if the DataStore contains BatchInfo and just take it directly from there if it does, falling back to conversion otherwise.

Furthermore, should BatchInfo be stored in Reference or Value format? I have it currently using Reference format since that better matches the results of the previous DataObject stuff, but GetBatchInfo automatically duplicates the batch info which makes it seem like it should be stored in Value format.

**Comment by deanljohnson** [comment] 2018-05-14 05:01
The IEnumerable<object> design has a bit of a gotcha - see [here](https://github.com/deanljohnson/duality/blob/f6b3aa4882c6e5b6746cfa25c4f02dacf19fcc37/Source/Editor/DualityEditor/Utility/Extensions/ExtMethodsDataObject.cs#L45-L52).

Because it is taking an IEnumerable, I could see people accidentally passing the result of a LINQ query into this method and then asking for the wrong type back. This all stems from the fact that the type of the passed in object is used as the format string in the DataObject. 

At first I thought to check the type of an object in the IEnumerable, but what if it is passed in as empty? Or, what if it is a derived type of the collection passed in (ie. an `Component[]` is passed with Transform elements)? We also can't walk the collection and find the common type because there might be multiple types that are common between the elements and we don't know what the call site is going to ask for.

Then I actually went with passing an additional 'elementType' parameter that would be the type of the individual elements being passed in and then be used in the format string. This was quite verbose as in almost every case the type was extremely evident at the calling site and made the API seem very noisy.

What might be a better idea is to have SetWrappedData take a `object[]` as then the calling site would have to be explicit about what they were passing in and it would make it a little more apparent what they should ask for when calling GetWrappedData.

Thoughts?

**Comment by deanljohnson** [comment] 2018-05-14 08:13
### Progress
- Added TryGet methods for other types and changed Contains/Get usages to TryGet where feasible
- Conducted tests for other types. Feeling pretty confident in the overall implementation now.
- Added many more unit tests
- Documented crucial parts of the code
- Fixed bugs in IColorData string parsing that would throw exceptions or otherwise behave strange. Copy/pasting the string "10,10,10,10,10" (5 values) onto a color field would throw and the string "10,10" (2 values) would create the color (10, 10, 0, 255) even though the string isn't a color.
- ConversionData now handles Reference and Value formatted data
- Lots of general bits of cleanup

Probably ready for a PR pretty soon. Might be pretty busy the next few days so don't know when I'll get the chance.

**Comment by ilexp** [comment] 2018-05-26 14:03
Done by @deanljohnson. Closing this.

**Closed by ilexp** 2018-05-26 14:03 UTC
Labels: Cleanup, Editor, Feature, Task
