### ISSUE TITLE
RequiredComponent with interfaces can create a nullreference exception

### ISSUE THREAD

**Issue by Barsonax** [AdamsLair/duality#587] opened 2017-10-26 11:56 UTC
### Summary

Adding a component to a gameobject with a RequiredComponent attribute that has a interface as type will result in a exception if that gameobject does not have a component with that interface. It seems to attempt to make a instance of that interface which is not possible since its a interface.

A better more clearer error message is needed than a nullreference exception. It should be clear to the user that you cannot add this component to a gameobject if that gameobject does not have a component that implements the required interface.

### How to reproduce [Bugs]

- Add the following code:
```csharp
public interface ITest { }

[RequiredComponent(typeof(ITest))]
public class Test : Component { }
```
-Try adding the Test component to a gameobject that does not have a component that implements ITest.
-Profit

### Workaround [Bugs]

- Just ignore the error

### Attachments

The error:
[Edit] Error:       NullReferenceException: Object reference not set to an instance of an object.
CallStack:
   at System.Object.GetType()
   at Duality.Editor.UndoRedoActions.CreateComponentAction.SetupComponentForEditing(Component cmp) in c:\projects\duality\Source\Editor\DualityEditor\UndoRedoActions\CreateComponentAction.cs:line 108
   at Duality.Editor.UndoRedoActions.CreateComponentAction.Do() in c:\projects\duality\Source\Editor\DualityEditor\UndoRedoActions\CreateComponentAction.cs:line 72
   at Duality.Editor.Plugins.SceneView.SceneView.CreateComponent(TreeNodeAdv baseNode, Type cmpType) in c:\projects\duality\Source\Plugins\EditorModules\SceneView\Modules\SceneView.cs:line 514
   at Duality.Editor.Plugins.SceneView.SceneView.newToolStripMenuItem_ItemClicked(Object sender, EventArgs e) in c:\projects\duality\Source\Plugins\EditorModules\SceneView\Modules\SceneView.cs:line 1531
   at AdamsLair.WinForms.ItemModels.MenuModelItem.RaisePerformAction() in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\ItemModels\MenuModelItem.cs:line 318
   at AdamsLair.WinForms.ItemViews.MenuStripMenuView.viewMenuItem_Click(Object sender, EventArgs e) in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\ItemViews\MenuStripMenuView.cs:line 306
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by ilexp** [comment] 2017-10-26 14:35
This is, for the most part, a usability bug because of not providing a descriptive error message. Other than that it is, as noted, expected behavior.

To fix this, an explicit check on this error condition should be introduced and an error should be logged. This could probably be done similarly to the existing circular constraint resolve errors, but finding a good spot to put this and check for it will be part of the todo. The existing unit tests could also be extended to check for error behavior and expect a log error at the appropriate time (init or instantiate? To be defined), but no exception.

Note: There is a second overload of `RequiredComponent` that is geared towards this use case by providing a concrete type to instantiate in case no component matching the interface is available.

**Comment by Barsonax** [comment] 2017-10-26 15:38
The overload is not fit for my case as I just wanted to let the user know he has to add a component that implements that interface to that gameobject. The user himself has to decide what component that will be.

**Comment by ilexp** [comment] 2017-10-26 16:22
> The overload is not fit for my case as I just wanted to let the user know he has to add a component that implements that interface to that gameobject. The user himself has to decide what component that will be.

It's just a default, not a strong connection. The user can still create the desired requirement component first and then add the new one, or switch out the required one later.

**Comment by Barsonax** [comment] 2018-04-09 13:19
An extension on top of a clear error message could be a dialog that lets the user choose the desired component to add to satisfy the requiredcomponent attribute.

**Comment by deanljohnson** [comment] 2018-05-17 18:04
This issue came up in a Discord and I want to summarize the discussion a little bit.

With the new support in the ListSelectionDialog for selecting component types, we could display a popup to the user when RequiredComponent cannot be satisfied that allows them to select the component type.

@Barsonax and I identified two possible implementations:
1. Display an error popup explaining the problem. If the user hits "OK", open the ListSelectionDialog to select the component implementing the interface.
2. Display the ListSelectionDialog immediately, but with an alternate header. Something like "The component you are adding requires one of the following components. Please select one."

The first option is cleaner code design because it keeps ListSelectionDialog from having too much responsibility, but we can probably still write a clean code design for this. The negative of the first one is that having multiple modal popup boxes gets annoying.

Option 2 is more user friendly.

**Comment by ilexp** [comment] 2018-05-17 20:09
Since the core is already behaving as expected - in this case with an error - I'd like to keep a potential fix for this mostly on the editor side. Instead of hooking into ComponentRequirementMap, it would also be possible to instead investigate the code in CreateComponentAction (see callstack in initial post) to find out how it would need to be extended to allow handling this case.

This could also be a good place for exploring the two options above:

> 1. Display an error popup explaining the problem. If the user hits "OK", open the ListSelectionDialog to select the component implementing the interface.
> 2. Display the ListSelectionDialog immediately, but with an alternate header. Something like "The component you are adding requires one of the following components. Please select one."

> The first option is cleaner code design because it keeps ListSelectionDialog from having too much responsibility, but it's a pretty minor issue. The negative of the first one is that having multiple modal popup boxes gets annoying.
> 
> I'd prefer option 2 myself - more user friendly.

I'd prefer option 2 as well, but I think the ListSelectionCode should have no knowledge of this at all. How about exposing some more properties for configuring the dialog as a general purpose editor tool instead? My suggestion for a starting point would be exposing an optional header text and type filtering as properties and configuring them where the dialog is created.

**Comment by deanljohnson** [comment] 2018-05-17 20:44
> Since the core is already behaving as expected - in this case with an error - I'd like to keep a potential fix for this mostly on the editor side. Instead of hooking into ComponentRequirementMap, it would also be possible to instead investigate the code in CreateComponentAction (see callstack in initial post) to find out how it would need to be extended to allow handling this case.

I agree that'd be cleaner. Here is a little brainstorm on this. In CreateComponentAction we get this:

`IEnumerable<Type> createRequirements = Component.RequireMap.GetRequirementsToCreate(this.targetParentObj, obj.GetType());`

After that call we could look at the RequiredComponent attribute and see if it would be satisfied by one of these types. If not, open the dialog to select a type. We would then have to pass the selected type back into `GetRequirementsToCreate` to make sure that the selected types own requirements are resolved. We'd then have to take the union of the original creation requirements with the requirements for the selected type. What we may have issues with there is that union operation may leave two components that satisfy the same requirement but came from different calls to GetRequirementsToCreate or the selection dialog. We may end up adding an extra component to the object that isn't needed.

**Comment by deanljohnson** [comment] 2018-05-18 19:55
Okay, I think I have something that works pretty well. First, here is the class setup:

```charp
public class D : Component, IRequirementInterface {}

[RequiredComponent(typeof(IRequirementInterface))]
public class C : Component , IRequirementInterface {}

[RequiredComponent(typeof(C))]
public class B : Component, IRequirementInterface {}

[RequiredComponent(typeof(IRequirementInterface))]
public class A : Component {}
```

And the results:

![required-interface](https://user-images.githubusercontent.com/12946946/40254882-ff580664-5a99-11e8-86e8-d5da238c2fa1.gif)

In the failure case there is no exception thrown and no undo/redo action is available.

**Comment by Barsonax** [comment] 2018-05-18 22:04
Wow that looks pretty good already. Instead of a exception we go to a really nice usability feature :).

**Comment by ilexp** [comment] 2018-05-19 09:14
> Edit: What do you all think should happen in the following case?
>
> ...
>
> The component is requiring a component with its own interface. Right now my implementation will say that Comp is satisfied and doesn't ask the user for an additional type to add.

It's a bit of a tricky case, but I think we should regard indirect self-requirements the same as direct self-requirements and ignore them. Unlike direct self-requirements, the core / `ComponentRequirementMap` will currently not discard interface requirements that are self-satisfied, so the interface will show up in the Component types requirement list and creation chain, but as long as your editor side algorithm can handle it accordingly, that should still be fine.

**Comment by ilexp** [comment] 2018-06-03 16:04
Done by @deanljohnson. Closing this.

**Closed by ilexp** 2018-06-03 16:04 UTC
Labels: Bug, Core, Nice2Have, Usability
