### ISSUE TITLE
Drag/drop does not work with prefabs

### ISSUE THREAD

**Issue by gregnk** [AdamsLair/duality#686] opened 2018-09-22 21:22 UTC
### Summary

When a prefab is drag-dropped into a scene or the object browser, it does not get added. Double-clicking the prefab to add it still works.

### Workaround

- As mentioned before, it is still possible to double-click on a prefab to add it to the scene

### Analysis

- The `OnDragDrop()` function is called when the prefab is drag-dropped, but it is not added to the scene

**Comment by ilexp** [comment] 2018-09-22 22:48
Thanks for reporting!

I just reproduced this in both v2.x and v3.0. Turns out, there was a recent change in a conversion operation that would fail in some cases, including Prefab dragdrop. 

I fixed it, updated both v2.x and v3.0 branches, and triggered a new binary release - should be out there in about 15 minutes. Dragging Prefabs into the Scene View or Cam View should work again after the update.

Closing this for now, but let me know if anything else comes up!

**Closed by ilexp** 2018-09-22 22:48 UTC
Labels: Bug, Critical, Editor, Usability
